// Argentina: 23 provinces + Buenos Aires Autonomous City
module.exports = {
  pageDir: "cs_america/argentina",
  source: { type: "natural-earth", iso_a2: "AR" },
  title: { ja: "アルゼンチンの州", en: "Provinces of Argentina" },
  defaultType: "province",
  tolerance: 0.02,
  typeOverrides: { "AR-C": "autonomous_city" },
  names: {
    "AR-A": { ja: "サルタ州",          en: "Salta" },
    "AR-B": { ja: "ブエノスアイレス州",en: "Buenos Aires" },
    "AR-C": { ja: "ブエノスアイレス自治市", en: "Autonomous City of Buenos Aires", note: "首都" },
    "AR-D": { ja: "サン・ルイス州",    en: "San Luis" },
    "AR-E": { ja: "エントレ・リオス州",en: "Entre Ríos" },
    "AR-F": { ja: "ラ・リオハ州",      en: "La Rioja" },
    "AR-G": { ja: "サンティアゴ・デル・エステロ州", en: "Santiago del Estero" },
    "AR-H": { ja: "チャコ州",          en: "Chaco" },
    "AR-J": { ja: "サン・フアン州",    en: "San Juan" },
    "AR-K": { ja: "カタマルカ州",      en: "Catamarca" },
    "AR-L": { ja: "ラ・パンパ州",      en: "La Pampa" },
    "AR-M": { ja: "メンドーサ州",      en: "Mendoza" },
    "AR-N": { ja: "ミシオネス州",      en: "Misiones" },
    "AR-P": { ja: "フォルモサ州",      en: "Formosa" },
    "AR-Q": { ja: "ネウケン州",        en: "Neuquén" },
    "AR-R": { ja: "リオネグロ州",      en: "Río Negro" },
    "AR-S": { ja: "サンタフェ州",      en: "Santa Fe" },
    "AR-T": { ja: "トゥクマン州",      en: "Tucumán" },
    "AR-U": { ja: "チュブ州",          en: "Chubut" },
    "AR-V": { ja: "ティエラ・デル・フエゴ州", en: "Tierra del Fuego" },
    "AR-W": { ja: "コリエンテス州",    en: "Corrientes" },
    "AR-X": { ja: "コルドバ州",        en: "Córdoba" },
    "AR-Y": { ja: "フフイ州",          en: "Jujuy" },
    "AR-Z": { ja: "サンタクルス州",    en: "Santa Cruz" },
  },
};
