// Brazil: 26 states + Federal District
module.exports = {
  pageDir: "cs_america/brazil",
  source: { type: "natural-earth", iso_a2: "BR" },
  title: { ja: "ブラジルの州", en: "States of Brazil" },
  defaultType: "state",
  tolerance: 0.02,
  typeOverrides: { "BR-DF": "federal_district" },
  names: {
    "BR-AC": { ja: "アクレ州",              en: "Acre" },
    "BR-AL": { ja: "アラゴアス州",          en: "Alagoas" },
    "BR-AP": { ja: "アマパー州",            en: "Amapá" },
    "BR-AM": { ja: "アマゾナス州",          en: "Amazonas" },
    "BR-BA": { ja: "バイーア州",            en: "Bahia" },
    "BR-CE": { ja: "セアラ州",              en: "Ceará" },
    "BR-DF": { ja: "ブラジリア連邦区",      en: "Federal District", note: "首都" },
    "BR-ES": { ja: "エスピリトサント州",    en: "Espírito Santo" },
    "BR-GO": { ja: "ゴイアス州",            en: "Goiás" },
    "BR-MA": { ja: "マラニョン州",          en: "Maranhão" },
    "BR-MT": { ja: "マットグロッソ州",      en: "Mato Grosso" },
    "BR-MS": { ja: "マットグロッソ・ド・スル州", en: "Mato Grosso do Sul" },
    "BR-MG": { ja: "ミナスジェライス州",    en: "Minas Gerais" },
    "BR-PA": { ja: "パラー州",              en: "Pará" },
    "BR-PB": { ja: "パライバ州",            en: "Paraíba" },
    "BR-PR": { ja: "パラナ州",              en: "Paraná" },
    "BR-PE": { ja: "ペルナンブコ州",        en: "Pernambuco" },
    "BR-PI": { ja: "ピアウイ州",            en: "Piauí" },
    "BR-RJ": { ja: "リオデジャネイロ州",    en: "Rio de Janeiro" },
    "BR-RN": { ja: "リオグランデ・ド・ノルテ州", en: "Rio Grande do Norte" },
    "BR-RS": { ja: "リオグランデ・ド・スル州",  en: "Rio Grande do Sul" },
    "BR-RO": { ja: "ロンドニア州",          en: "Rondônia" },
    "BR-RR": { ja: "ロライマ州",            en: "Roraima" },
    "BR-SC": { ja: "サンタカタリーナ州",    en: "Santa Catarina" },
    "BR-SP": { ja: "サンパウロ州",          en: "São Paulo" },
    "BR-SE": { ja: "セルジペ州",            en: "Sergipe" },
    "BR-TO": { ja: "トカンチンス州",        en: "Tocantins" },
  },
};
