// Bulgaria: 28 provinces (oblast)
module.exports = {
  pageDir: "europe/bulgaria",
  source: { type: "natural-earth", iso_a2: "BG" },
  title: { ja: "ブルガリアの州", en: "Provinces of Bulgaria" },
  defaultType: "province",
  tolerance: 0.01,
  minOuterArea: 1e-4,
  names: {
    "BG-01": { ja: "ブラゴエヴグラト州", en: "Blagoevgrad" },
    "BG-02": { ja: "ブルガス州",      en: "Burgas" },
    "BG-03": { ja: "ヴァルナ州",      en: "Varna" },
    "BG-04": { ja: "ヴェリコ・タルノヴォ州", en: "Veliko Tarnovo" },
    "BG-05": { ja: "ヴィディン州",    en: "Vidin" },
    "BG-06": { ja: "ヴラツァ州",      en: "Vratsa" },
    "BG-07": { ja: "ガブロヴォ州",    en: "Gabrovo" },
    "BG-08": { ja: "ドブリチ州",      en: "Dobrich" },
    "BG-09": { ja: "クルジャリ州",    en: "Kardzhali" },
    "BG-10": { ja: "キュステンディル州",en: "Kyustendil" },
    "BG-11": { ja: "ロヴェチ州",      en: "Lovech" },
    "BG-12": { ja: "モンタナ州",      en: "Montana" },
    "BG-13": { ja: "パザルジク州",    en: "Pazardzhik" },
    "BG-14": { ja: "ペルニク州",      en: "Pernik" },
    "BG-15": { ja: "プレヴェン州",    en: "Pleven" },
    "BG-16": { ja: "プロヴディフ州",  en: "Plovdiv" },
    "BG-17": { ja: "ラズグラド州",    en: "Razgrad" },
    "BG-18": { ja: "ルセ州",          en: "Ruse" },
    "BG-19": { ja: "シリストラ州",    en: "Silistra" },
    "BG-20": { ja: "スリヴェン州",    en: "Sliven" },
    "BG-21": { ja: "スモリャン州",    en: "Smolyan" },
    "BG-22": { ja: "ソフィア市",      en: "Sofia (City)", note: "首都" },
    "BG-23": { ja: "ソフィア州",      en: "Sofia (Province)" },
    "BG-24": { ja: "スタラ・ザゴラ州",en: "Stara Zagora" },
    "BG-25": { ja: "タルゴヴィシテ州",en: "Targovishte" },
    "BG-26": { ja: "ハスコヴォ州",    en: "Haskovo" },
    "BG-27": { ja: "シュメン州",      en: "Shumen" },
    "BG-28": { ja: "ヤンボル州",      en: "Yambol" },
  },
};
