// China: 22 provinces + 5 autonomous regions + 4 direct-administered municipalities
//        + 2 SARs (Hong Kong, Macao). NE has 32 features (excluding Taiwan).
module.exports = {
  pageDir: "asia/china",
  source: { type: "natural-earth", iso_a2: "CN" },
  title: { ja: "中国の省・自治区・直轄市", en: "Provincial-level administrative divisions of China" },
  defaultType: "province",
  tolerance: 0.05,
  minOuterArea: 5e-3,
  typeOverrides: {
    "CN-BJ": "metropolitan_city", "CN-TJ": "metropolitan_city",
    "CN-SH": "metropolitan_city", "CN-CQ": "metropolitan_city",
    "CN-NX": "autonomous_community", "CN-XJ": "autonomous_community",
    "CN-NM": "autonomous_community", "CN-XZ": "autonomous_community",
    "CN-GX": "autonomous_community",
  },
  names: {
    "CN-BJ": { ja: "北京市",     en: "Beijing", note: "首都" },
    "CN-TJ": { ja: "天津市",     en: "Tianjin" },
    "CN-SH": { ja: "上海市",     en: "Shanghai" },
    "CN-CQ": { ja: "重慶市",     en: "Chongqing" },
    "CN-HE": { ja: "河北省",     en: "Hebei" },
    "CN-SX": { ja: "山西省",     en: "Shanxi" },
    "CN-LN": { ja: "遼寧省",     en: "Liaoning" },
    "CN-JL": { ja: "吉林省",     en: "Jilin" },
    "CN-HL": { ja: "黒竜江省",   en: "Heilongjiang" },
    "CN-JS": { ja: "江蘇省",     en: "Jiangsu" },
    "CN-ZJ": { ja: "浙江省",     en: "Zhejiang" },
    "CN-AH": { ja: "安徽省",     en: "Anhui" },
    "CN-FJ": { ja: "福建省",     en: "Fujian" },
    "CN-JX": { ja: "江西省",     en: "Jiangxi" },
    "CN-SD": { ja: "山東省",     en: "Shandong" },
    "CN-HA": { ja: "河南省",     en: "Henan" },
    "CN-HB": { ja: "湖北省",     en: "Hubei" },
    "CN-HN": { ja: "湖南省",     en: "Hunan" },
    "CN-GD": { ja: "広東省",     en: "Guangdong" },
    "CN-HI": { ja: "海南省",     en: "Hainan" },
    "CN-SC": { ja: "四川省",     en: "Sichuan" },
    "CN-GZ": { ja: "貴州省",     en: "Guizhou" },
    "CN-YN": { ja: "雲南省",     en: "Yunnan" },
    "CN-SN": { ja: "陝西省",     en: "Shaanxi" },
    "CN-GS": { ja: "甘粛省",     en: "Gansu" },
    "CN-QH": { ja: "青海省",     en: "Qinghai" },
    "CN-NX": { ja: "寧夏回族自治区", en: "Ningxia" },
    "CN-XJ": { ja: "新疆ウイグル自治区", en: "Xinjiang" },
    "CN-NM": { ja: "内モンゴル自治区", en: "Inner Mongolia" },
    "CN-XZ": { ja: "チベット自治区", en: "Tibet" },
    "CN-GX": { ja: "広西チワン族自治区", en: "Guangxi" },
    "CN-HK": { ja: "香港特別行政区", en: "Hong Kong" },
    "CN-MO": { ja: "マカオ特別行政区", en: "Macau" },
  },
};
