// Colombia: 32 departments + Bogotá Capital District
module.exports = {
  pageDir: "cs_america/colombia",
  source: { type: "natural-earth", iso_a2: "CO" },
  title: { ja: "コロンビアの県", en: "Departments of Colombia" },
  defaultType: "department",
  tolerance: 0.02,
  typeOverrides: { "CO-DC": "federal_district" },
  names: {
    "CO-AMA": { ja: "アマソナス県",          en: "Amazonas" },
    "CO-ANT": { ja: "アンティオキア県",      en: "Antioquia" },
    "CO-ARA": { ja: "アラウカ県",            en: "Arauca" },
    "CO-ATL": { ja: "アトランティコ県",      en: "Atlántico" },
    "CO-BOL": { ja: "ボリーバル県",          en: "Bolívar" },
    "CO-BOY": { ja: "ボヤカ県",              en: "Boyacá" },
    "CO-CAL": { ja: "カルダス県",            en: "Caldas" },
    "CO-CAQ": { ja: "カケタ県",              en: "Caquetá" },
    "CO-CAS": { ja: "カサナレ県",            en: "Casanare" },
    "CO-CAU": { ja: "カウカ県",              en: "Cauca" },
    "CO-CES": { ja: "セサル県",              en: "Cesar" },
    "CO-CHO": { ja: "チョコ県",              en: "Chocó" },
    "CO-COR": { ja: "コルドバ県",            en: "Córdoba" },
    "CO-CUN": { ja: "クンディナマルカ県",    en: "Cundinamarca" },
    "CO-DC":  { ja: "首都ボゴタ",            en: "Bogotá", note: "首都" },
    "CO-GUA": { ja: "ラ・グアヒラ県",        en: "La Guajira" },
    "CO-GUV": { ja: "グアビアレ県",          en: "Guaviare" },
    "CO-GNA": { ja: "グアイニア県",          en: "Guainía" },
    "CO-HUI": { ja: "ウイラ県",              en: "Huila" },
    "CO-LAG": { ja: "ラ・グアヒラ県",        en: "La Guajira" },
    "CO-MAG": { ja: "マグダレナ県",          en: "Magdalena" },
    "CO-MET": { ja: "メタ県",                en: "Meta" },
    "CO-NAR": { ja: "ナリーニョ県",          en: "Nariño" },
    "CO-NSA": { ja: "ノルテ・デ・サンタンデル県", en: "Norte de Santander" },
    "CO-PUT": { ja: "プトゥマヨ県",          en: "Putumayo" },
    "CO-QUI": { ja: "キンディオ県",          en: "Quindío" },
    "CO-RIS": { ja: "リサラルダ県",          en: "Risaralda" },
    "CO-SAN": { ja: "サンタンデル県",        en: "Santander" },
    "CO-SAP": { ja: "サン・アンドレス諸島県",en: "San Andrés" },
    "CO-SUC": { ja: "スクレ県",              en: "Sucre" },
    "CO-TOL": { ja: "トリマ県",              en: "Tolima" },
    "CO-VAC": { ja: "バジェ・デル・カウカ県",en: "Valle del Cauca" },
    "CO-VAU": { ja: "バウペス県",            en: "Vaupés" },
    "CO-VID": { ja: "ビチャダ県",            en: "Vichada" },
  },
};
