// Croatia: 20 counties + Zagreb (NE has 21)
module.exports = {
  pageDir: "europe/croatia",
  source: { type: "natural-earth", iso_a2: "HR" },
  title: { ja: "クロアチアの県", en: "Counties of Croatia" },
  defaultType: "county",
  tolerance: 0.01,
  minOuterArea: 1e-4,
  typeOverrides: { "HR-21": "metropolitan_city" },
  names: {
    "HR-01": { ja: "ザグレブ郡",       en: "Zagreb County" },
    "HR-02": { ja: "クラピナ・ザゴリエ郡", en: "Krapina-Zagorje" },
    "HR-03": { ja: "シサク・モスラビナ郡", en: "Sisak-Moslavina" },
    "HR-04": { ja: "カルロヴァツ郡",   en: "Karlovac" },
    "HR-05": { ja: "ヴァラジュディン郡",en: "Varaždin" },
    "HR-06": { ja: "コプリヴニツァ・クリジェヴツィ郡", en: "Koprivnica-Križevci" },
    "HR-07": { ja: "ビェロヴァル・ビロゴラ郡", en: "Bjelovar-Bilogora" },
    "HR-08": { ja: "プリモリェ・ゴルスキー・コタール郡", en: "Primorje-Gorski Kotar" },
    "HR-09": { ja: "リカ・セニ郡",     en: "Lika-Senj" },
    "HR-10": { ja: "ヴィロヴィティツァ・ポドラヴィナ郡", en: "Virovitica-Podravina" },
    "HR-11": { ja: "ポジェガ・スラヴォニア郡", en: "Požega-Slavonia" },
    "HR-12": { ja: "ブロド・ポサヴィナ郡", en: "Brod-Posavina" },
    "HR-13": { ja: "ザダル郡",         en: "Zadar" },
    "HR-14": { ja: "オシイェク・バラニャ郡", en: "Osijek-Baranja" },
    "HR-15": { ja: "シベニク・クニン郡",en: "Šibenik-Knin" },
    "HR-16": { ja: "ヴコヴァル・スリイェム郡", en: "Vukovar-Srijem" },
    "HR-17": { ja: "スプリト・ダルマチア郡", en: "Split-Dalmatia" },
    "HR-18": { ja: "イストラ郡",       en: "Istria" },
    "HR-19": { ja: "ドゥブロヴニク・ネレトヴァ郡", en: "Dubrovnik-Neretva" },
    "HR-20": { ja: "メジムリエ郡",     en: "Međimurje" },
    "HR-21": { ja: "ザグレブ市",       en: "Zagreb (City)", note: "首都" },
  },
};
