// Egypt: 27 governorates
module.exports = {
  pageDir: "africa/egypt",
  source: { type: "natural-earth", iso_a2: "EG" },
  title: { ja: "エジプトの県", en: "Governorates of Egypt" },
  defaultType: "department",
  tolerance: 0.03,
  minOuterArea: 1e-3,
  names: {
    "EG-DK": { ja: "ダカリーヤ県",       en: "Dakahlia" },
    "EG-BA": { ja: "紅海県",             en: "Red Sea" },
    "EG-BH": { ja: "ブハイラ県",         en: "Beheira" },
    "EG-FYM":{ ja: "ファイユーム県",     en: "Faiyum" },
    "EG-GH": { ja: "ガルビーヤ県",       en: "Gharbia" },
    "EG-ALX":{ ja: "アレクサンドリア県", en: "Alexandria" },
    "EG-IS": { ja: "イスマイリア県",     en: "Ismailia" },
    "EG-GZ": { ja: "ギーザ県",           en: "Giza" },
    "EG-MNF":{ ja: "ミヌフィーヤ県",     en: "Monufia" },
    "EG-MN": { ja: "ミニヤー県",         en: "Minya" },
    "EG-C":  { ja: "カイロ県",           en: "Cairo", note: "首都" },
    "EG-KB": { ja: "カリュビーヤ県",     en: "Qalyubia" },
    "EG-LX": { ja: "ルクソール県",       en: "Luxor" },
    "EG-WAD":{ ja: "新峡谷県",           en: "New Valley" },
    "EG-SUZ":{ ja: "スエズ県",           en: "Suez" },
    "EG-SHR":{ ja: "シャルキーヤ県",     en: "Sharqia" },
    "EG-ASN":{ ja: "アスワン県",         en: "Aswan" },
    "EG-AST":{ ja: "アシュート県",       en: "Asyut" },
    "EG-BNS":{ ja: "バニー・スエフ県",   en: "Beni Suef" },
    "EG-PTS":{ ja: "ポートサイド県",     en: "Port Said" },
    "EG-DT": { ja: "ダミエッタ県",       en: "Damietta" },
    "EG-JS": { ja: "南シナイ県",         en: "South Sinai" },
    "EG-KFS":{ ja: "カフル・エル・シェイフ県", en: "Kafr El Sheikh" },
    "EG-MT": { ja: "マトルーフ県",       en: "Matrouh" },
    "EG-KN": { ja: "キナ県",             en: "Qena" },
    "EG-SIN":{ ja: "北シナイ県",         en: "North Sinai" },
    "EG-SHG":{ ja: "ソハーグ県",         en: "Sohag" },
  },
};
