// Guatemala: 22 departments. Natural Earth uses GT-XX codes.
module.exports = {
  pageDir: "n_america/guatemala",
  source: { type: "natural-earth", iso_a2: "GT" },
  title: { ja: "グアテマラの県", en: "Departments of Guatemala" },
  defaultType: "department",
  tolerance: 0.01,
  minOuterArea: 1e-4,
  names: {
    "GT-AV": { ja: "アルタ・ベラパス県",  en: "Alta Verapaz" },
    "GT-BV": { ja: "バハ・ベラパス県",    en: "Baja Verapaz" },
    "GT-CM": { ja: "チマルテナンゴ県",    en: "Chimaltenango" },
    "GT-CQ": { ja: "チキムラ県",          en: "Chiquimula" },
    "GT-PR": { ja: "エル・プログレソ県",  en: "El Progreso" },
    "GT-ES": { ja: "エスクィントラ県",    en: "Escuintla" },
    "GT-GU": { ja: "グアテマラ県",        en: "Guatemala", note: "首都所在地" },
    "GT-HU": { ja: "ウェウェテナンゴ県",  en: "Huehuetenango" },
    "GT-IZ": { ja: "イサバル県",          en: "Izabal" },
    "GT-JA": { ja: "ハラパ県",            en: "Jalapa" },
    "GT-JU": { ja: "フティアパ県",        en: "Jutiapa" },
    "GT-PE": { ja: "ペテン県",            en: "Petén" },
    "GT-QZ": { ja: "ケツァルテナンゴ県",  en: "Quetzaltenango" },
    "GT-QC": { ja: "キチェ県",            en: "Quiché" },
    "GT-RE": { ja: "レタルレウ県",        en: "Retalhuleu" },
    "GT-SA": { ja: "サカテペケス県",      en: "Sacatepéquez" },
    "GT-SM": { ja: "サン・マルコス県",    en: "San Marcos" },
    "GT-SR": { ja: "サンタ・ローサ県",    en: "Santa Rosa" },
    "GT-SO": { ja: "ソロラ県",            en: "Sololá" },
    "GT-SU": { ja: "スチテペケス県",      en: "Suchitepéquez" },
    "GT-TO": { ja: "トトニカパン県",      en: "Totonicapán" },
    "GT-ZA": { ja: "サカパ県",            en: "Zacapa" },
  },
};
