// Hungary: 19 counties + 1 capital (Budapest) + 23 cities of county rights (NE: 43)
module.exports = {
  pageDir: "europe/hungary",
  source: { type: "natural-earth", iso_a2: "HU" },
  title: { ja: "ハンガリーの県", en: "Counties of Hungary" },
  defaultType: "county",
  tolerance: 0.008,
  minOuterArea: 1e-4,
  typeOverrides: { "HU-BU": "metropolitan_city" },
  names: {
    "HU-BU": { ja: "ブダペスト",       en: "Budapest", note: "首都" },
    "HU-BK": { ja: "バーチ・キシュクン県", en: "Bács-Kiskun" },
    "HU-BA": { ja: "バラニャ県",       en: "Baranya" },
    "HU-BE": { ja: "ベーケーシュ県",   en: "Békés" },
    "HU-BZ": { ja: "ボルショド・アバウーイ・ゼンプレーン県", en: "Borsod-Abaúj-Zemplén" },
    "HU-CS": { ja: "チョングラード・チャナード県", en: "Csongrád-Csanád" },
    "HU-FE": { ja: "フェイェール県",   en: "Fejér" },
    "HU-GS": { ja: "ジェール・モション・ショプロン県", en: "Győr-Moson-Sopron" },
    "HU-HB": { ja: "ハイドゥー・ビハル県", en: "Hajdú-Bihar" },
    "HU-HE": { ja: "ヘヴェシュ県",     en: "Heves" },
    "HU-JN": { ja: "ヤース・ナジクン・ソルノク県", en: "Jász-Nagykun-Szolnok" },
    "HU-KE": { ja: "コマーロム・エステルゴム県", en: "Komárom-Esztergom" },
    "HU-NO": { ja: "ノーグラード県",   en: "Nógrád" },
    "HU-PE": { ja: "ペシュト県",       en: "Pest" },
    "HU-SO": { ja: "シャモジ県",       en: "Somogy" },
    "HU-SZ": { ja: "サボルチ・サトマール・ベレグ県", en: "Szabolcs-Szatmár-Bereg" },
    "HU-TO": { ja: "トルナ県",         en: "Tolna" },
    "HU-VA": { ja: "ヴァシュ県",       en: "Vas" },
    "HU-VE": { ja: "ヴェスプレーム県", en: "Veszprém" },
    "HU-ZA": { ja: "ザラ県",           en: "Zala" },
  },
};
