// India: 28 states + 8 union territories = 36
module.exports = {
  pageDir: "asia/india",
  source: { type: "natural-earth", iso_a2: "IN" },
  title: { ja: "インドの州・連邦直轄地", en: "States and Union Territories of India" },
  defaultType: "state",
  tolerance: 0.03,
  minOuterArea: 1e-3,
  typeOverrides: {
    "IN-AN": "territory", "IN-CH": "territory", "IN-DH": "territory",
    "IN-DD": "territory", "IN-DL": "territory", "IN-JK": "territory",
    "IN-LA": "territory", "IN-LD": "territory", "IN-PY": "territory",
  },
  names: {
    "IN-AP": { ja: "アンドラ・プラデーシュ州",     en: "Andhra Pradesh" },
    "IN-AR": { ja: "アルナーチャル・プラデーシュ州", en: "Arunachal Pradesh" },
    "IN-AS": { ja: "アッサム州",                   en: "Assam" },
    "IN-BR": { ja: "ビハール州",                   en: "Bihar" },
    "IN-CT": { ja: "チャッティースガル州",         en: "Chhattisgarh" },
    "IN-GA": { ja: "ゴア州",                       en: "Goa" },
    "IN-GJ": { ja: "グジャラート州",               en: "Gujarat" },
    "IN-HR": { ja: "ハリヤーナー州",               en: "Haryana" },
    "IN-HP": { ja: "ヒマーチャル・プラデーシュ州", en: "Himachal Pradesh" },
    "IN-JH": { ja: "ジャールカンド州",             en: "Jharkhand" },
    "IN-KA": { ja: "カルナータカ州",               en: "Karnataka" },
    "IN-KL": { ja: "ケーララ州",                   en: "Kerala" },
    "IN-MP": { ja: "マディヤ・プラデーシュ州",     en: "Madhya Pradesh" },
    "IN-MH": { ja: "マハーラーシュトラ州",         en: "Maharashtra" },
    "IN-MN": { ja: "マニプル州",                   en: "Manipur" },
    "IN-ML": { ja: "メーガーラヤ州",               en: "Meghalaya" },
    "IN-MZ": { ja: "ミゾラム州",                   en: "Mizoram" },
    "IN-NL": { ja: "ナガランド州",                 en: "Nagaland" },
    "IN-OR": { ja: "オリッサ州",                   en: "Odisha" },
    "IN-OD": { ja: "オリッサ州",                   en: "Odisha" },
    "IN-PB": { ja: "パンジャーブ州",               en: "Punjab" },
    "IN-RJ": { ja: "ラージャスターン州",           en: "Rajasthan" },
    "IN-SK": { ja: "シッキム州",                   en: "Sikkim" },
    "IN-TN": { ja: "タミル・ナードゥ州",           en: "Tamil Nadu" },
    "IN-TG": { ja: "テランガナ州",                 en: "Telangana" },
    "IN-TR": { ja: "トリプラ州",                   en: "Tripura" },
    "IN-UP": { ja: "ウッタル・プラデーシュ州",     en: "Uttar Pradesh" },
    "IN-UT": { ja: "ウッタラーカンド州",           en: "Uttarakhand" },
    "IN-UK": { ja: "ウッタラーカンド州",           en: "Uttarakhand" },
    "IN-WB": { ja: "西ベンガル州",                 en: "West Bengal" },
    "IN-AN": { ja: "アンダマン・ニコバル諸島",     en: "Andaman and Nicobar Islands" },
    "IN-CH": { ja: "チャンディーガル",             en: "Chandigarh" },
    "IN-DH": { ja: "ダードラ・ナガル・ハヴェリー", en: "Dadra and Nagar Haveli" },
    "IN-DD": { ja: "ダマン・ディーウ",             en: "Daman and Diu" },
    "IN-DL": { ja: "デリー首都圏",                 en: "Delhi", note: "首都" },
    "IN-JK": { ja: "ジャンムー・カシミール",       en: "Jammu and Kashmir" },
    "IN-LA": { ja: "ラダック",                     en: "Ladakh" },
    "IN-LD": { ja: "ラクシャドウィープ諸島",       en: "Lakshadweep" },
    "IN-PY": { ja: "プドゥッチェリー",             en: "Puducherry" },
  },
};
