// Indonesia: 38 provinces (NE has 33 — older boundaries). We use NE as-is;
// curated names cover the major ones.
module.exports = {
  pageDir: "asia/indonesia",
  source: { type: "natural-earth", iso_a2: "ID" },
  title: { ja: "インドネシアの州", en: "Provinces of Indonesia" },
  defaultType: "province",
  tolerance: 0.03,
  minOuterArea: 1e-3,
  names: {
    "ID-AC": { ja: "アチェ州",                   en: "Aceh" },
    "ID-BA": { ja: "バリ州",                     en: "Bali" },
    "ID-BB": { ja: "バンカ・ブリトゥン諸島州",   en: "Bangka Belitung" },
    "ID-BE": { ja: "ブンクル州",                 en: "Bengkulu" },
    "ID-BT": { ja: "バンテン州",                 en: "Banten" },
    "ID-GO": { ja: "ゴロンタロ州",               en: "Gorontalo" },
    "ID-JA": { ja: "ジャンビ州",                 en: "Jambi" },
    "ID-JB": { ja: "西ジャワ州",                 en: "West Java" },
    "ID-JI": { ja: "東ジャワ州",                 en: "East Java" },
    "ID-JK": { ja: "ジャカルタ首都特別州",       en: "Jakarta", note: "首都" },
    "ID-JT": { ja: "中部ジャワ州",               en: "Central Java" },
    "ID-JW": { ja: "ジャワ",                     en: "Java" },
    "ID-KB": { ja: "西カリマンタン州",           en: "West Kalimantan" },
    "ID-KI": { ja: "東カリマンタン州",           en: "East Kalimantan" },
    "ID-KR": { ja: "リアウ諸島州",               en: "Riau Islands" },
    "ID-KS": { ja: "南カリマンタン州",           en: "South Kalimantan" },
    "ID-KT": { ja: "中部カリマンタン州",         en: "Central Kalimantan" },
    "ID-KU": { ja: "北カリマンタン州",           en: "North Kalimantan" },
    "ID-LA": { ja: "ランプン州",                 en: "Lampung" },
    "ID-MA": { ja: "マルク州",                   en: "Maluku" },
    "ID-MU": { ja: "北マルク州",                 en: "North Maluku" },
    "ID-NB": { ja: "西ヌサ・トゥンガラ州",       en: "West Nusa Tenggara" },
    "ID-NT": { ja: "東ヌサ・トゥンガラ州",       en: "East Nusa Tenggara" },
    "ID-PA": { ja: "パプア州",                   en: "Papua" },
    "ID-PB": { ja: "西パプア州",                 en: "West Papua" },
    "ID-RI": { ja: "リアウ州",                   en: "Riau" },
    "ID-SA": { ja: "北スラウェシ州",             en: "North Sulawesi" },
    "ID-SB": { ja: "西スマトラ州",               en: "West Sumatra" },
    "ID-SG": { ja: "東南スラウェシ州",           en: "Southeast Sulawesi" },
    "ID-SN": { ja: "南スラウェシ州",             en: "South Sulawesi" },
    "ID-SR": { ja: "西スラウェシ州",             en: "West Sulawesi" },
    "ID-SS": { ja: "南スマトラ州",               en: "South Sumatra" },
    "ID-ST": { ja: "中部スラウェシ州",           en: "Central Sulawesi" },
    "ID-SU": { ja: "北スマトラ州",               en: "North Sumatra" },
    "ID-YO": { ja: "ジョグジャカルタ特別州",     en: "Yogyakarta" },
  },
};
