// Ireland: 26 traditional counties of the Republic. NE has 34 (more granular).
module.exports = {
  pageDir: "europe/ireland",
  source: { type: "natural-earth", iso_a2: "IE" },
  title: { ja: "アイルランドの県", en: "Counties of Ireland" },
  defaultType: "county",
  tolerance: 0.01,
  minOuterArea: 1e-4,
  names: {
    "IE-CW": { ja: "カーロウ県",     en: "Carlow" },
    "IE-CN": { ja: "キャヴァン県",   en: "Cavan" },
    "IE-CE": { ja: "クレア県",       en: "Clare" },
    "IE-CO": { ja: "コーク県",       en: "Cork" },
    "IE-DL": { ja: "ドニゴール県",   en: "Donegal" },
    "IE-D":  { ja: "ダブリン県",     en: "Dublin", note: "首都" },
    "IE-G":  { ja: "ゴールウェイ県", en: "Galway" },
    "IE-KY": { ja: "ケリー県",       en: "Kerry" },
    "IE-KE": { ja: "キルデア県",     en: "Kildare" },
    "IE-KK": { ja: "キルケニー県",   en: "Kilkenny" },
    "IE-LS": { ja: "リーシュ県",     en: "Laois" },
    "IE-LM": { ja: "リートリム県",   en: "Leitrim" },
    "IE-LK": { ja: "リムリック県",   en: "Limerick" },
    "IE-LD": { ja: "ロングフォード県", en: "Longford" },
    "IE-LH": { ja: "ラウス県",       en: "Louth" },
    "IE-MO": { ja: "メイヨー県",     en: "Mayo" },
    "IE-MH": { ja: "ミーズ県",       en: "Meath" },
    "IE-MN": { ja: "モナハン県",     en: "Monaghan" },
    "IE-OY": { ja: "オファリー県",   en: "Offaly" },
    "IE-RN": { ja: "ロスコモン県",   en: "Roscommon" },
    "IE-SO": { ja: "スライゴ県",     en: "Sligo" },
    "IE-TA": { ja: "ティペラリー県", en: "Tipperary" },
    "IE-WD": { ja: "ウォーターフォード県", en: "Waterford" },
    "IE-WH": { ja: "ウェストミース県", en: "Westmeath" },
    "IE-WX": { ja: "ウェックスフォード県", en: "Wexford" },
    "IE-WW": { ja: "ウィックロー県", en: "Wicklow" },
  },
};
