// Italy: 20 regions
module.exports = {
  pageDir: "europe/italy",
  source: {
    type: "url",
    url: "https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson",
  },
  title: { ja: "イタリアの州", en: "Regions of Italy" },
  defaultType: "region",
  tolerance: 0.015,
  codeOf: (f) => f.properties.reg_istat_code,
  nameOf: (f) => f.properties.reg_name,
  names: {
    "01": { ja: "ピエモンテ州",                    en: "Piemonte" },
    "02": { ja: "ヴァッレ・ダオスタ州",            en: "Valle d'Aosta" },
    "03": { ja: "ロンバルディア州",                en: "Lombardia" },
    "04": { ja: "トレンティーノ・アルト・アディジェ州", en: "Trentino-Alto Adige" },
    "05": { ja: "ヴェネト州",                      en: "Veneto" },
    "06": { ja: "フリウリ・ヴェネツィア・ジュリア州", en: "Friuli-Venezia Giulia" },
    "07": { ja: "リグーリア州",                    en: "Liguria" },
    "08": { ja: "エミリア・ロマーニャ州",          en: "Emilia-Romagna" },
    "09": { ja: "トスカーナ州",                    en: "Toscana" },
    "10": { ja: "ウンブリア州",                    en: "Umbria" },
    "11": { ja: "マルケ州",                        en: "Marche" },
    "12": { ja: "ラツィオ州",                      en: "Lazio", note: "首都ローマ" },
    "13": { ja: "アブルッツォ州",                  en: "Abruzzo" },
    "14": { ja: "モリーゼ州",                      en: "Molise" },
    "15": { ja: "カンパニア州",                    en: "Campania" },
    "16": { ja: "プッリャ州",                      en: "Puglia" },
    "17": { ja: "バジリカータ州",                  en: "Basilicata" },
    "18": { ja: "カラブリア州",                    en: "Calabria" },
    "19": { ja: "シチリア州",                      en: "Sicilia" },
    "20": { ja: "サルデーニャ州",                  en: "Sardegna" },
  },
};
