// South Korea: 17 administrative divisions (provinces & metropolitan cities).
// The actual SVG was generated by a separate older script; we only use this
// config for compute-projection.cjs to know the geographic bbox.
module.exports = {
  pageDir: "asia/korea",
  source: { type: "natural-earth", iso_a2: "KR" },
  title: { ja: "韓国の広域自治体", en: "Administrative Divisions of South Korea" },
  defaultType: "province",
  tolerance: 0.01,
  minOuterArea: 1e-4,
};
