// Mexico: 31 states + Mexico City
module.exports = {
  pageDir: "n_america/mexico",
  source: { type: "natural-earth", iso_a2: "MX" },
  title: { ja: "メキシコの州", en: "States of Mexico" },
  defaultType: "state",
  tolerance: 0.02,
  typeOverrides: { "MX-DIF": "federal_district", "MX-CMX": "federal_district" },
  names: {
    "MX-AGU": { ja: "アグアスカリエンテス州",          en: "Aguascalientes" },
    "MX-BCN": { ja: "バハ・カリフォルニア州",          en: "Baja California" },
    "MX-BCS": { ja: "バハ・カリフォルニア・スール州",  en: "Baja California Sur" },
    "MX-CAM": { ja: "カンペチェ州",                    en: "Campeche" },
    "MX-CHP": { ja: "チアパス州",                      en: "Chiapas" },
    "MX-CHH": { ja: "チワワ州",                        en: "Chihuahua" },
    "MX-COA": { ja: "コアウイラ州",                    en: "Coahuila" },
    "MX-COL": { ja: "コリマ州",                        en: "Colima" },
    "MX-DIF": { ja: "メキシコシティ",                  en: "Mexico City", note: "首都" },
    "MX-CMX": { ja: "メキシコシティ",                  en: "Mexico City", note: "首都" },
    "MX-DUR": { ja: "ドゥランゴ州",                    en: "Durango" },
    "MX-GUA": { ja: "グアナフアト州",                  en: "Guanajuato" },
    "MX-GRO": { ja: "ゲレーロ州",                      en: "Guerrero" },
    "MX-HID": { ja: "イダルゴ州",                      en: "Hidalgo" },
    "MX-JAL": { ja: "ハリスコ州",                      en: "Jalisco" },
    "MX-MEX": { ja: "メキシコ州",                      en: "México" },
    "MX-MIC": { ja: "ミチョアカン州",                  en: "Michoacán" },
    "MX-MOR": { ja: "モレロス州",                      en: "Morelos" },
    "MX-NAY": { ja: "ナヤリット州",                    en: "Nayarit" },
    "MX-NLE": { ja: "ヌエボ・レオン州",                en: "Nuevo León" },
    "MX-OAX": { ja: "オアハカ州",                      en: "Oaxaca" },
    "MX-PUE": { ja: "プエブラ州",                      en: "Puebla" },
    "MX-QUE": { ja: "ケレタロ州",                      en: "Querétaro" },
    "MX-ROO": { ja: "キンタナ・ロー州",                en: "Quintana Roo" },
    "MX-SLP": { ja: "サン・ルイス・ポトシ州",          en: "San Luis Potosí" },
    "MX-SIN": { ja: "シナロア州",                      en: "Sinaloa" },
    "MX-SON": { ja: "ソノラ州",                        en: "Sonora" },
    "MX-TAB": { ja: "タバスコ州",                      en: "Tabasco" },
    "MX-TAM": { ja: "タマウリパス州",                  en: "Tamaulipas" },
    "MX-TLA": { ja: "トラスカラ州",                    en: "Tlaxcala" },
    "MX-VER": { ja: "ベラクルス州",                    en: "Veracruz" },
    "MX-YUC": { ja: "ユカタン州",                      en: "Yucatán" },
    "MX-ZAC": { ja: "サカテカス州",                    en: "Zacatecas" },
  },
};
