// Nigeria: 36 states + Federal Capital Territory
module.exports = {
  pageDir: "africa/nigeria",
  source: { type: "natural-earth", iso_a2: "NG" },
  title: { ja: "ナイジェリアの州", en: "States of Nigeria" },
  defaultType: "state",
  tolerance: 0.02,
  minOuterArea: 1e-3,
  typeOverrides: { "NG-FC": "federal_district" },
  names: {
    "NG-AB": { ja: "アビア州",       en: "Abia" },
    "NG-AD": { ja: "アダマワ州",     en: "Adamawa" },
    "NG-AK": { ja: "アクワ・イボム州", en: "Akwa Ibom" },
    "NG-AN": { ja: "アナンブラ州",   en: "Anambra" },
    "NG-BA": { ja: "バウチ州",       en: "Bauchi" },
    "NG-BY": { ja: "バイエルサ州",   en: "Bayelsa" },
    "NG-BE": { ja: "ベヌエ州",       en: "Benue" },
    "NG-BO": { ja: "ボルノ州",       en: "Borno" },
    "NG-CR": { ja: "クロス・リバー州", en: "Cross River" },
    "NG-DE": { ja: "デルタ州",       en: "Delta" },
    "NG-EB": { ja: "エボニ州",       en: "Ebonyi" },
    "NG-ED": { ja: "エド州",         en: "Edo" },
    "NG-EK": { ja: "エキティ州",     en: "Ekiti" },
    "NG-EN": { ja: "エヌグ州",       en: "Enugu" },
    "NG-FC": { ja: "アブジャ連邦首都地区", en: "Federal Capital Territory", note: "首都アブジャ" },
    "NG-GO": { ja: "ゴンベ州",       en: "Gombe" },
    "NG-IM": { ja: "イモ州",         en: "Imo" },
    "NG-JI": { ja: "ジガワ州",       en: "Jigawa" },
    "NG-KD": { ja: "カドゥナ州",     en: "Kaduna" },
    "NG-KN": { ja: "カノ州",         en: "Kano" },
    "NG-KT": { ja: "カツィナ州",     en: "Katsina" },
    "NG-KE": { ja: "ケッビ州",       en: "Kebbi" },
    "NG-KO": { ja: "コギ州",         en: "Kogi" },
    "NG-KW": { ja: "クワラ州",       en: "Kwara" },
    "NG-LA": { ja: "ラゴス州",       en: "Lagos", note: "最大都市" },
    "NG-NA": { ja: "ナサラワ州",     en: "Nasarawa" },
    "NG-NI": { ja: "ニジェール州",   en: "Niger" },
    "NG-OG": { ja: "オグン州",       en: "Ogun" },
    "NG-ON": { ja: "オンド州",       en: "Ondo" },
    "NG-OS": { ja: "オスン州",       en: "Osun" },
    "NG-OY": { ja: "オヨ州",         en: "Oyo" },
    "NG-PL": { ja: "プラトー州",     en: "Plateau" },
    "NG-RI": { ja: "リバーズ州",     en: "Rivers" },
    "NG-SO": { ja: "ソコト州",       en: "Sokoto" },
    "NG-TA": { ja: "タラバ州",       en: "Taraba" },
    "NG-YO": { ja: "ヨベ州",         en: "Yobe" },
    "NG-ZA": { ja: "ザムファラ州",   en: "Zamfara" },
  },
};
