// Peru: 24 departments + Constitutional Province of Callao
module.exports = {
  pageDir: "cs_america/peru",
  source: { type: "natural-earth", iso_a2: "PE" },
  title: { ja: "ペルーの県", en: "Departments of Peru" },
  defaultType: "department",
  tolerance: 0.02,
  names: {
    "PE-AMA": { ja: "アマソナス県",       en: "Amazonas" },
    "PE-ANC": { ja: "アンカシュ県",       en: "Áncash" },
    "PE-APU": { ja: "アプリマック県",     en: "Apurímac" },
    "PE-ARE": { ja: "アレキパ県",         en: "Arequipa" },
    "PE-AYA": { ja: "アヤクチョ県",       en: "Ayacucho" },
    "PE-CAJ": { ja: "カハマルカ県",       en: "Cajamarca" },
    "PE-CAL": { ja: "カヤオ憲法特別区",   en: "Callao", note: "憲法特別区" },
    "PE-CUS": { ja: "クスコ県",           en: "Cusco" },
    "PE-HUV": { ja: "ウアンカベリカ県",   en: "Huancavelica" },
    "PE-HUC": { ja: "ウアヌコ県",         en: "Huánuco" },
    "PE-ICA": { ja: "イカ県",             en: "Ica" },
    "PE-JUN": { ja: "フニン県",           en: "Junín" },
    "PE-LAL": { ja: "ラ・リベルタ県",     en: "La Libertad" },
    "PE-LAM": { ja: "ランバイェケ県",     en: "Lambayeque" },
    "PE-LIM": { ja: "リマ県",             en: "Lima", note: "首都" },
    "PE-LOR": { ja: "ロレト県",           en: "Loreto" },
    "PE-MDD": { ja: "マードレ・デ・ディオス県", en: "Madre de Dios" },
    "PE-MOQ": { ja: "モケグア県",         en: "Moquegua" },
    "PE-PAS": { ja: "パスコ県",           en: "Pasco" },
    "PE-PIU": { ja: "ピウラ県",           en: "Piura" },
    "PE-PUN": { ja: "プノ県",             en: "Puno" },
    "PE-SAM": { ja: "サン・マルティン県", en: "San Martín" },
    "PE-TAC": { ja: "タクナ県",           en: "Tacna" },
    "PE-TUM": { ja: "トゥンベス県",       en: "Tumbes" },
    "PE-UCA": { ja: "ウカヤリ県",         en: "Ucayali" },
  },
};
