// Philippines: 80 provinces (NE has 118 features incl. highly-urbanized
// cities and independent municipalities — we filter to provinces only).
module.exports = {
  pageDir: "asia/philippines",
  source: { type: "natural-earth", iso_a2: "PH" },
  title: { ja: "フィリピンの州", en: "Provinces of the Philippines" },
  defaultType: "province",
  tolerance: 0.02,
  minOuterArea: 1e-3,
  // Keep only provinces (drop highly-urbanized cities, etc.) to keep the
  // first-level admin count under 100 and visually clear.
  featureFilter: (f) => f.properties.type_en === "Province",
  // Curated names — primary cities and well-known provinces. Fallbacks use
  // the source data's English/Tagalog name.
  names: {
    "PH-MNL": { ja: "マニラ首都圏",       en: "Manila", note: "首都" },
    "PH-CEB": { ja: "セブ州",             en: "Cebu" },
    "PH-LUN": { ja: "ラ・ウニオン州",     en: "La Union" },
    "PH-LAG": { ja: "ラグナ州",           en: "Laguna" },
    "PH-BAN": { ja: "バターン州",         en: "Bataan" },
    "PH-BTG": { ja: "バタンガス州",       en: "Batangas" },
    "PH-BUL": { ja: "ブラカン州",         en: "Bulacan" },
    "PH-CAV": { ja: "カビテ州",           en: "Cavite" },
    "PH-PAM": { ja: "パンパンガ州",       en: "Pampanga" },
    "PH-RIZ": { ja: "リサール州",         en: "Rizal" },
    "PH-PAN": { ja: "パンガシナン州",     en: "Pangasinan" },
    "PH-NUE": { ja: "ヌエバ・エシハ州",   en: "Nueva Ecija" },
    "PH-ZMB": { ja: "サンバレス州",       en: "Zambales" },
    "PH-TAR": { ja: "タルラック州",       en: "Tarlac" },
    "PH-ILS": { ja: "南イロコス州",       en: "Ilocos Sur" },
    "PH-ILN": { ja: "北イロコス州",       en: "Ilocos Norte" },
    "PH-CAG": { ja: "カガヤン州",         en: "Cagayan" },
    "PH-ISA": { ja: "イサベラ州",         en: "Isabela" },
    "PH-NUV": { ja: "ヌエバ・ビスカヤ州", en: "Nueva Vizcaya" },
    "PH-QUI": { ja: "キリノ州",           en: "Quirino" },
    "PH-BAS": { ja: "バシラン州",         en: "Basilan" },
    "PH-BTN": { ja: "バターネス州",       en: "Batanes" },
    "PH-IFU": { ja: "イフガオ州",         en: "Ifugao" },
    "PH-KAL": { ja: "カリンガ州",         en: "Kalinga" },
    "PH-MOU": { ja: "山岳州",             en: "Mountain Province" },
    "PH-ABR": { ja: "アブラ州",           en: "Abra" },
    "PH-APA": { ja: "アパヤオ州",         en: "Apayao" },
    "PH-BEN": { ja: "ベンゲット州",       en: "Benguet" },
    "PH-AUR": { ja: "アウロラ州",         en: "Aurora" },
    "PH-QUE": { ja: "ケソン州",           en: "Quezon" },
    "PH-CAN": { ja: "北カマリネス州",     en: "Camarines Norte" },
    "PH-CAS": { ja: "南カマリネス州",     en: "Camarines Sur" },
    "PH-ALB": { ja: "アルバイ州",         en: "Albay" },
    "PH-CAT": { ja: "カタンドゥアネス州", en: "Catanduanes" },
    "PH-MAS": { ja: "マスバテ州",         en: "Masbate" },
    "PH-SOR": { ja: "ソルソゴン州",       en: "Sorsogon" },
    "PH-MAD": { ja: "マリンドゥケ州",     en: "Marinduque" },
    "PH-ROM": { ja: "ロンブロン州",       en: "Romblon" },
    "PH-MDC": { ja: "西ミンドロ州",       en: "Occidental Mindoro" },
    "PH-MDR": { ja: "東ミンドロ州",       en: "Oriental Mindoro" },
    "PH-PLW": { ja: "パラワン州",         en: "Palawan" },
    "PH-AKL": { ja: "アクラン州",         en: "Aklan" },
    "PH-ANT": { ja: "アンティーケ州",     en: "Antique" },
    "PH-CAP": { ja: "カピス州",           en: "Capiz" },
    "PH-GUI": { ja: "ギマラス州",         en: "Guimaras" },
    "PH-ILI": { ja: "イロイロ州",         en: "Iloilo" },
    "PH-NEC": { ja: "西ネグロス州",       en: "Negros Occidental" },
    "PH-NER": { ja: "東ネグロス州",       en: "Negros Oriental" },
    "PH-SIG": { ja: "シキホール州",       en: "Siquijor" },
    "PH-BOH": { ja: "ボホール州",         en: "Bohol" },
    "PH-EAS": { ja: "東サマール州",       en: "Eastern Samar" },
    "PH-LEY": { ja: "レイテ州",           en: "Leyte" },
    "PH-NSA": { ja: "北サマール州",       en: "Northern Samar" },
    "PH-WSA": { ja: "サマール州",         en: "Samar" },
    "PH-SLE": { ja: "南レイテ州",         en: "Southern Leyte" },
    "PH-BIL": { ja: "ビリラン州",         en: "Biliran" },
    "PH-ZSI": { ja: "サンボアンガ・シブガイ州", en: "Zamboanga Sibugay" },
    "PH-ZAN": { ja: "北サンボアンガ州",   en: "Zamboanga del Norte" },
    "PH-ZAS": { ja: "南サンボアンガ州",   en: "Zamboanga del Sur" },
    "PH-BUK": { ja: "ブキドノン州",       en: "Bukidnon" },
    "PH-CAM": { ja: "カミギン州",         en: "Camiguin" },
    "PH-LAN": { ja: "北ラナオ州",         en: "Lanao del Norte" },
    "PH-LAS": { ja: "南ラナオ州",         en: "Lanao del Sur" },
    "PH-MSC": { ja: "西ミサミス州",       en: "Misamis Occidental" },
    "PH-MSR": { ja: "東ミサミス州",       en: "Misamis Oriental" },
    "PH-COM": { ja: "ダバオ・デ・オロ州", en: "Davao de Oro" },
    "PH-DAV": { ja: "北ダバオ州",         en: "Davao del Norte" },
    "PH-DAS": { ja: "南ダバオ州",         en: "Davao del Sur" },
    "PH-DAO": { ja: "東ダバオ州",         en: "Davao Oriental" },
    "PH-DVO": { ja: "西ダバオ州",         en: "Davao Occidental" },
    "PH-NCO": { ja: "北コタバト州",       en: "North Cotabato" },
    "PH-SUK": { ja: "スルタン・クダラット州", en: "Sultan Kudarat" },
    "PH-SAR": { ja: "サランガニ州",       en: "Sarangani" },
    "PH-SCO": { ja: "南コタバト州",       en: "South Cotabato" },
    "PH-AGN": { ja: "北アグサン州",       en: "Agusan del Norte" },
    "PH-AGS": { ja: "南アグサン州",       en: "Agusan del Sur" },
    "PH-DIN": { ja: "ディナガット諸島州", en: "Dinagat Islands" },
    "PH-SUN": { ja: "北スリガオ州",       en: "Surigao del Norte" },
    "PH-SUR": { ja: "南スリガオ州",       en: "Surigao del Sur" },
    "PH-MAG": { ja: "マギンダナオ州",     en: "Maguindanao" },
    "PH-SLU": { ja: "スールー州",         en: "Sulu" },
    "PH-TAW": { ja: "タウィタウィ州",     en: "Tawi-Tawi" },
  },
};
