// Romania: 41 counties (județe) + Bucharest municipality
module.exports = {
  pageDir: "europe/romania",
  source: { type: "natural-earth", iso_a2: "RO" },
  title: { ja: "ルーマニアの県", en: "Counties of Romania" },
  defaultType: "department",
  tolerance: 0.01,
  minOuterArea: 1e-4,
  typeOverrides: { "RO-B": "metropolitan_city" },
  names: {
    "RO-AB": { ja: "アルバ県",        en: "Alba" },
    "RO-AR": { ja: "アラド県",        en: "Arad" },
    "RO-AG": { ja: "アルジェシュ県",  en: "Argeș" },
    "RO-BC": { ja: "バカウ県",        en: "Bacău" },
    "RO-BH": { ja: "ビホル県",        en: "Bihor" },
    "RO-BN": { ja: "ビストリツァ・ナサウド県", en: "Bistrița-Năsăud" },
    "RO-BT": { ja: "ボトシャニ県",    en: "Botoșani" },
    "RO-BV": { ja: "ブラショフ県",    en: "Brașov" },
    "RO-BR": { ja: "ブライラ県",      en: "Brăila" },
    "RO-B":  { ja: "ブカレスト",      en: "Bucharest", note: "首都" },
    "RO-BZ": { ja: "ブザウ県",        en: "Buzău" },
    "RO-CS": { ja: "カラシュ・セヴェリン県", en: "Caraș-Severin" },
    "RO-CL": { ja: "カララシ県",      en: "Călărași" },
    "RO-CJ": { ja: "クルージュ県",    en: "Cluj" },
    "RO-CT": { ja: "コンスタンツァ県",en: "Constanța" },
    "RO-CV": { ja: "コヴァスナ県",    en: "Covasna" },
    "RO-DB": { ja: "ドゥンボヴィツァ県", en: "Dâmbovița" },
    "RO-DJ": { ja: "ドルジュ県",      en: "Dolj" },
    "RO-GL": { ja: "ガラツィ県",      en: "Galați" },
    "RO-GR": { ja: "ジュルジュ県",    en: "Giurgiu" },
    "RO-GJ": { ja: "ゴルジュ県",      en: "Gorj" },
    "RO-HR": { ja: "ハルギタ県",      en: "Harghita" },
    "RO-HD": { ja: "フネドアラ県",    en: "Hunedoara" },
    "RO-IL": { ja: "イアロミツァ県",  en: "Ialomița" },
    "RO-IS": { ja: "ヤシ県",          en: "Iași" },
    "RO-IF": { ja: "イルフォフ県",    en: "Ilfov" },
    "RO-MM": { ja: "マラムレシュ県",  en: "Maramureș" },
    "RO-MH": { ja: "メヘディンツィ県",en: "Mehedinți" },
    "RO-MS": { ja: "ムレシュ県",      en: "Mureș" },
    "RO-NT": { ja: "ネアムツ県",      en: "Neamț" },
    "RO-OT": { ja: "オルト県",        en: "Olt" },
    "RO-PH": { ja: "プラホヴァ県",    en: "Prahova" },
    "RO-SM": { ja: "サトゥ・マレ県",  en: "Satu Mare" },
    "RO-SJ": { ja: "サラジュ県",      en: "Sălaj" },
    "RO-SB": { ja: "シビウ県",        en: "Sibiu" },
    "RO-SV": { ja: "スチャヴァ県",    en: "Suceava" },
    "RO-TR": { ja: "テレオルマン県",  en: "Teleorman" },
    "RO-TM": { ja: "ティミシュ県",    en: "Timiș" },
    "RO-TL": { ja: "トゥルチャ県",    en: "Tulcea" },
    "RO-VS": { ja: "ヴァスルイ県",    en: "Vaslui" },
    "RO-VL": { ja: "ヴルチャ県",      en: "Vâlcea" },
    "RO-VN": { ja: "ヴランチャ県",    en: "Vrancea" },
  },
};
