// Russia: 85 federal subjects (NE has 86 incl. disputed Crimea + Sevastopol).
// Subject types: Republic / Region / Territory (Krai) / Federal City /
// Autonomous Region / Autonomous Province (Okrug). For simplicity we group
// most as "oblast" (the broad Japanese sense of 州) and use specific labels
// for republics and federal cities.
module.exports = {
  pageDir: "asia/russia",
  source: { type: "natural-earth", iso_a2: "RU" },
  title: { ja: "ロシアの連邦構成主体", en: "Federal Subjects of Russia" },
  defaultType: "oblast",
  tolerance: 0.15,
  minOuterArea: 5e-3,
  // Drop placeholder features (X01~)
  featureFilter: (f) => !/X\d/.test(String(f.properties.iso_3166_2 || "")),
  typeOverrides: {
    "RU-MOS": "metropolitan_city",
    "RU-SPE": "metropolitan_city",
    "RU-AL":  "autonomous_community",
    "RU-BA":  "autonomous_community",
    "RU-BU":  "autonomous_community",
    "RU-CE":  "autonomous_community",
    "RU-CU":  "autonomous_community",
    "RU-DA":  "autonomous_community",
    "RU-IN":  "autonomous_community",
    "RU-KB":  "autonomous_community",
    "RU-KC":  "autonomous_community",
    "RU-KK":  "autonomous_community",
    "RU-KL":  "autonomous_community",
    "RU-KO":  "autonomous_community",
    "RU-KR":  "autonomous_community",
    "RU-ME":  "autonomous_community",
    "RU-MO":  "autonomous_community",
    "RU-SA":  "autonomous_community",
    "RU-SE":  "autonomous_community",
    "RU-TA":  "autonomous_community",
    "RU-TY":  "autonomous_community",
    "RU-UD":  "autonomous_community",
    "RU-AD":  "autonomous_community",
  },
  names: {
    "RU-MOS": { ja: "モスクワ",                    en: "Moscow", note: "首都" },
    "RU-SPE": { ja: "サンクトペテルブルク",        en: "Saint Petersburg" },
    "RU-MOW": { ja: "モスクワ州",                  en: "Moscow Oblast" },
    "RU-LEN": { ja: "レニングラード州",            en: "Leningrad Oblast" },
    "RU-KGD": { ja: "カリーニングラード州",        en: "Kaliningrad Oblast" },
    "RU-MUR": { ja: "ムルマンスク州",              en: "Murmansk Oblast" },
    "RU-ARK": { ja: "アルハンゲリスク州",          en: "Arkhangelsk Oblast" },
    "RU-VLG": { ja: "ヴォログダ州",                en: "Vologda Oblast" },
    "RU-KR":  { ja: "カレリア共和国",              en: "Karelia" },
    "RU-NGR": { ja: "ノヴゴロド州",                en: "Novgorod Oblast" },
    "RU-PSK": { ja: "プスコフ州",                  en: "Pskov Oblast" },
    "RU-TVE": { ja: "トヴェリ州",                  en: "Tver Oblast" },
    "RU-SMO": { ja: "スモレンスク州",              en: "Smolensk Oblast" },
    "RU-BRY": { ja: "ブリャンスク州",              en: "Bryansk Oblast" },
    "RU-KLU": { ja: "カルーガ州",                  en: "Kaluga Oblast" },
    "RU-TUL": { ja: "トゥーラ州",                  en: "Tula Oblast" },
    "RU-RYA": { ja: "リャザン州",                  en: "Ryazan Oblast" },
    "RU-VLA": { ja: "ウラジーミル州",              en: "Vladimir Oblast" },
    "RU-YAR": { ja: "ヤロスラヴリ州",              en: "Yaroslavl Oblast" },
    "RU-KOS": { ja: "コストロマ州",                en: "Kostroma Oblast" },
    "RU-IVA": { ja: "イヴァノヴォ州",              en: "Ivanovo Oblast" },
    "RU-ORL": { ja: "オリョール州",                en: "Oryol Oblast" },
    "RU-KRS": { ja: "クルスク州",                  en: "Kursk Oblast" },
    "RU-BEL": { ja: "ベルゴロド州",                en: "Belgorod Oblast" },
    "RU-VOR": { ja: "ヴォロネジ州",                en: "Voronezh Oblast" },
    "RU-LIP": { ja: "リペツク州",                  en: "Lipetsk Oblast" },
    "RU-TAM": { ja: "タンボフ州",                  en: "Tambov Oblast" },
    "RU-PNZ": { ja: "ペンザ州",                    en: "Penza Oblast" },
    "RU-NIZ": { ja: "ニジニ・ノヴゴロド州",        en: "Nizhny Novgorod Oblast" },
    "RU-ULY": { ja: "ウリヤノフスク州",            en: "Ulyanovsk Oblast" },
    "RU-SAM": { ja: "サマラ州",                    en: "Samara Oblast" },
    "RU-SAR": { ja: "サラトフ州",                  en: "Saratov Oblast" },
    "RU-VGG": { ja: "ヴォルゴグラード州",          en: "Volgograd Oblast" },
    "RU-AST": { ja: "アストラハン州",              en: "Astrakhan Oblast" },
    "RU-ROS": { ja: "ロストフ州",                  en: "Rostov Oblast" },
    "RU-KDA": { ja: "クラスノダール地方",          en: "Krasnodar Krai" },
    "RU-STA": { ja: "スタヴロポリ地方",            en: "Stavropol Krai" },
    "RU-AD":  { ja: "アディゲ共和国",              en: "Adygea" },
    "RU-KL":  { ja: "カルムイク共和国",            en: "Kalmykia" },
    "RU-DA":  { ja: "ダゲスタン共和国",            en: "Dagestan" },
    "RU-CE":  { ja: "チェチェン共和国",            en: "Chechnya" },
    "RU-IN":  { ja: "イングーシ共和国",            en: "Ingushetia" },
    "RU-SE":  { ja: "北オセチア共和国",            en: "North Ossetia" },
    "RU-KB":  { ja: "カバルダ・バルカル共和国",    en: "Kabardino-Balkaria" },
    "RU-KC":  { ja: "カラチャイ・チェルケス共和国",en: "Karachay-Cherkessia" },
    "RU-CU":  { ja: "チュヴァシ共和国",            en: "Chuvashia" },
    "RU-MO":  { ja: "モルドヴィア共和国",          en: "Mordovia" },
    "RU-ME":  { ja: "マリ・エル共和国",            en: "Mari El" },
    "RU-TA":  { ja: "タタールスタン共和国",        en: "Tatarstan" },
    "RU-UD":  { ja: "ウドムルト共和国",            en: "Udmurtia" },
    "RU-BA":  { ja: "バシコルトスタン共和国",      en: "Bashkortostan" },
    "RU-PER": { ja: "ペルミ地方",                  en: "Perm Krai" },
    "RU-KO":  { ja: "コミ共和国",                  en: "Komi" },
    "RU-NEN": { ja: "ネネツ自治管区",              en: "Nenets Autonomous Okrug", type: "territory" },
    "RU-KIR": { ja: "キーロフ州",                  en: "Kirov Oblast" },
    "RU-ORE": { ja: "オレンブルク州",              en: "Orenburg Oblast" },
    "RU-SVE": { ja: "スヴェルドロフスク州",        en: "Sverdlovsk Oblast" },
    "RU-CHE": { ja: "チェリャビンスク州",          en: "Chelyabinsk Oblast" },
    "RU-KGN": { ja: "クルガン州",                  en: "Kurgan Oblast" },
    "RU-TYU": { ja: "チュメニ州",                  en: "Tyumen Oblast" },
    "RU-KHM": { ja: "ハンティ・マンシ自治管区",    en: "Khanty-Mansi Autonomous Okrug", type: "territory" },
    "RU-YAN": { ja: "ヤマロ・ネネツ自治管区",      en: "Yamalo-Nenets Autonomous Okrug", type: "territory" },
    "RU-OMS": { ja: "オムスク州",                  en: "Omsk Oblast" },
    "RU-NVS": { ja: "ノヴォシビルスク州",          en: "Novosibirsk Oblast" },
    "RU-TOM": { ja: "トムスク州",                  en: "Tomsk Oblast" },
    "RU-KEM": { ja: "ケメロヴォ州",                en: "Kemerovo Oblast" },
    "RU-ALT": { ja: "アルタイ地方",                en: "Altai Krai" },
    "RU-AL":  { ja: "アルタイ共和国",              en: "Altai Republic" },
    "RU-KK":  { ja: "ハカス共和国",                en: "Khakassia" },
    "RU-TY":  { ja: "トゥヴァ共和国",              en: "Tuva" },
    "RU-KYA": { ja: "クラスノヤルスク地方",        en: "Krasnoyarsk Krai" },
    "RU-IRK": { ja: "イルクーツク州",              en: "Irkutsk Oblast" },
    "RU-BU":  { ja: "ブリヤート共和国",            en: "Buryatia" },
    "RU-ZAB": { ja: "ザバイカル地方",              en: "Zabaykalsky Krai" },
    "RU-AMU": { ja: "アムール州",                  en: "Amur Oblast" },
    "RU-SA":  { ja: "サハ共和国（ヤクート）",      en: "Sakha (Yakutia)" },
    "RU-MAG": { ja: "マガダン州",                  en: "Magadan Oblast" },
    "RU-CHU": { ja: "チュコト自治管区",            en: "Chukotka Autonomous Okrug", type: "territory" },
    "RU-KAM": { ja: "カムチャツカ地方",            en: "Kamchatka Krai" },
    "RU-PRI": { ja: "沿海地方",                    en: "Primorsky Krai" },
    "RU-KHA": { ja: "ハバロフスク地方",            en: "Khabarovsk Krai" },
    "RU-SAK": { ja: "サハリン州",                  en: "Sakhalin Oblast" },
    "RU-YEV": { ja: "ユダヤ自治州",                en: "Jewish Autonomous Oblast", type: "territory" },
    "UA-43":  { ja: "クリミア共和国",              en: "Crimea", note: "ロシアが実効支配（国際的には係争中）" },
    "UA-40":  { ja: "セヴァストポリ",              en: "Sevastopol", note: "ロシアが実効支配（国際的には係争中）" },
  },
};
