// Spain: 17 autonomous communities + 2 autonomous cities (Ceuta, Melilla)
module.exports = {
  pageDir: "europe/spain",
  source: {
    type: "url",
    url: "https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/spain-communities.geojson",
  },
  title: { ja: "スペインの自治州", en: "Autonomous Communities of Spain" },
  defaultType: "autonomous_community",
  tolerance: 0.015,
  codeOf: (f) => f.properties.cod_ccaa,
  nameOf: (f) => f.properties.name,
  typeOverrides: { "18": "autonomous_city", "19": "autonomous_city" },
  names: {
    "01": { ja: "アンダルシア州",      en: "Andalucía" },
    "02": { ja: "アラゴン州",          en: "Aragón" },
    "03": { ja: "アストゥリアス州",    en: "Asturias" },
    "04": { ja: "バレアレス諸島州",    en: "Illes Balears" },
    "05": { ja: "カナリア諸島州",      en: "Canarias" },
    "06": { ja: "カンタブリア州",      en: "Cantabria" },
    "07": { ja: "カスティーリャ・イ・レオン州", en: "Castilla y León" },
    "08": { ja: "カスティーリャ・ラ・マンチャ州", en: "Castilla-La Mancha" },
    "09": { ja: "カタルーニャ州",      en: "Cataluña" },
    "10": { ja: "バレンシア州",        en: "Valencia" },
    "11": { ja: "エストレマドゥーラ州",en: "Extremadura" },
    "12": { ja: "ガリシア州",          en: "Galicia" },
    "13": { ja: "マドリード州",        en: "Madrid", note: "首都" },
    "14": { ja: "ムルシア州",          en: "Murcia" },
    "15": { ja: "ナバーラ州",          en: "Navarra" },
    "16": { ja: "バスク州",            en: "País Vasco" },
    "17": { ja: "ラ・リオハ州",        en: "La Rioja" },
    "18": { ja: "セウタ自治都市",      en: "Ceuta" },
    "19": { ja: "メリリャ自治都市",    en: "Melilla" },
  },
};
