// Sweden: 21 counties (län)
module.exports = {
  pageDir: "europe/sweden",
  source: { type: "natural-earth", iso_a2: "SE" },
  title: { ja: "スウェーデンの県", en: "Counties of Sweden" },
  defaultType: "county",
  tolerance: 0.02,
  minOuterArea: 1e-3,
  names: {
    "SE-K":  { ja: "ブレーキンゲ県",        en: "Blekinge" },
    "SE-W":  { ja: "ダーラナ県",            en: "Dalarna" },
    "SE-X":  { ja: "イェヴレボリ県",        en: "Gävleborg" },
    "SE-I":  { ja: "ゴットランド県",        en: "Gotland" },
    "SE-N":  { ja: "ハッランド県",          en: "Halland" },
    "SE-Z":  { ja: "イェムトランド県",      en: "Jämtland" },
    "SE-F":  { ja: "ヨンショーピング県",    en: "Jönköping" },
    "SE-H":  { ja: "カルマル県",            en: "Kalmar" },
    "SE-G":  { ja: "クロノベリ県",          en: "Kronoberg" },
    "SE-BD": { ja: "ノールボッテン県",      en: "Norrbotten" },
    "SE-T":  { ja: "エレブルー県",          en: "Örebro" },
    "SE-E":  { ja: "エステルイェートランド県", en: "Östergötland" },
    "SE-M":  { ja: "スコーネ県",            en: "Skåne" },
    "SE-D":  { ja: "セーデルマンランド県",  en: "Södermanland" },
    "SE-AB": { ja: "ストックホルム県",      en: "Stockholm", note: "首都" },
    "SE-C":  { ja: "ウプサラ県",            en: "Uppsala" },
    "SE-S":  { ja: "ヴェルムランド県",      en: "Värmland" },
    "SE-AC": { ja: "ヴェステルボッテン県",  en: "Västerbotten" },
    "SE-Y":  { ja: "ヴェステルノールランド県", en: "Västernorrland" },
    "SE-U":  { ja: "ヴェストマンランド県",  en: "Västmanland" },
    "SE-O":  { ja: "ヴェストラ・イェータランド県", en: "Västra Götaland" },
  },
};
