// Switzerland: 26 cantons
module.exports = {
  pageDir: "europe/switzerland",
  source: { type: "natural-earth", iso_a2: "CH" },
  title: { ja: "スイスの州（カントン）", en: "Cantons of Switzerland" },
  defaultType: "canton",
  tolerance: 0.005,
  minOuterArea: 1e-4,
  names: {
    "CH-AG": { ja: "アールガウ州",           en: "Aargau" },
    "CH-AI": { ja: "アッペンツェル・インナーローデン準州", en: "Appenzell Innerrhoden" },
    "CH-AR": { ja: "アッペンツェル・アウサーローデン準州", en: "Appenzell Ausserrhoden" },
    "CH-BE": { ja: "ベルン州",                en: "Bern", note: "首都" },
    "CH-BL": { ja: "バーゼル・ラント準州",   en: "Basel-Landschaft" },
    "CH-BS": { ja: "バーゼル・シュタット準州",en: "Basel-Stadt" },
    "CH-FR": { ja: "フリブール州",            en: "Fribourg" },
    "CH-GE": { ja: "ジュネーヴ州",            en: "Genève" },
    "CH-GL": { ja: "グラールス州",            en: "Glarus" },
    "CH-GR": { ja: "グラウビュンデン州",      en: "Graubünden" },
    "CH-JU": { ja: "ジュラ州",                en: "Jura" },
    "CH-LU": { ja: "ルツェルン州",            en: "Luzern" },
    "CH-NE": { ja: "ヌーシャテル州",          en: "Neuchâtel" },
    "CH-NW": { ja: "ニトヴァルデン準州",      en: "Nidwalden" },
    "CH-OW": { ja: "オプヴァルデン準州",      en: "Obwalden" },
    "CH-SG": { ja: "ザンクトガレン州",        en: "St. Gallen" },
    "CH-SH": { ja: "シャフハウゼン州",        en: "Schaffhausen" },
    "CH-SO": { ja: "ゾロトゥルン州",          en: "Solothurn" },
    "CH-SZ": { ja: "シュヴィーツ州",          en: "Schwyz" },
    "CH-TG": { ja: "トゥールガウ州",          en: "Thurgau" },
    "CH-TI": { ja: "ティチーノ州",            en: "Ticino" },
    "CH-UR": { ja: "ウーリ州",                en: "Uri" },
    "CH-VD": { ja: "ヴォー州",                en: "Vaud" },
    "CH-VS": { ja: "ヴァレー州",              en: "Valais" },
    "CH-ZG": { ja: "ツーク州",                en: "Zug" },
    "CH-ZH": { ja: "チューリッヒ州",          en: "Zürich" },
  },
};
