// Taiwan: 22 cities and counties (NE has 21; treats some merged)
module.exports = {
  pageDir: "asia/taiwan",
  source: { type: "natural-earth", iso_a2: "TW" },
  title: { ja: "台湾の県・市", en: "Counties and Cities of Taiwan" },
  defaultType: "city",
  tolerance: 0.01,
  minOuterArea: 1e-4,
  typeOverrides: {
    "TW-HSQ": "county", "TW-MIA": "county", "TW-CHA": "county",
    "TW-NAN": "county", "TW-YUN": "county", "TW-CYI": "county",
    "TW-PIF": "county", "TW-ILA": "county", "TW-HUA": "county", "TW-TTT": "county",
    "TW-PEN": "county", "TW-KIN": "county", "TW-LIE": "county",
  },
  names: {
    "TW-TPE": { ja: "台北市",       en: "Taipei", note: "首都" },
    "TW-NWT": { ja: "新北市",       en: "New Taipei" },
    "TW-TAO": { ja: "桃園市",       en: "Taoyuan" },
    "TW-TXG": { ja: "台中市",       en: "Taichung" },
    "TW-TNN": { ja: "台南市",       en: "Tainan" },
    "TW-KHH": { ja: "高雄市",       en: "Kaohsiung" },
    "TW-KEE": { ja: "基隆市",       en: "Keelung" },
    "TW-HSZ": { ja: "新竹市",       en: "Hsinchu City" },
    "TW-CYQ": { ja: "嘉義市",       en: "Chiayi City" },
    "TW-HSQ": { ja: "新竹県",       en: "Hsinchu County" },
    "TW-MIA": { ja: "苗栗県",       en: "Miaoli" },
    "TW-CHA": { ja: "彰化県",       en: "Changhua" },
    "TW-NAN": { ja: "南投県",       en: "Nantou" },
    "TW-YUN": { ja: "雲林県",       en: "Yunlin" },
    "TW-CYI": { ja: "嘉義県",       en: "Chiayi County" },
    "TW-PIF": { ja: "屏東県",       en: "Pingtung" },
    "TW-ILA": { ja: "宜蘭県",       en: "Yilan" },
    "TW-HUA": { ja: "花蓮県",       en: "Hualien" },
    "TW-TTT": { ja: "台東県",       en: "Taitung" },
    "TW-PEN": { ja: "澎湖県",       en: "Penghu" },
    "TW-KIN": { ja: "金門県",       en: "Kinmen" },
    "TW-LIE": { ja: "連江県",       en: "Lienchiang", note: "馬祖列島" },
  },
};
