// Thailand: 76 provinces + Bangkok Metropolis
module.exports = {
  pageDir: "asia/thai",
  source: { type: "natural-earth", iso_a2: "TH" },
  title: { ja: "タイの県", en: "Provinces of Thailand" },
  defaultType: "province",
  tolerance: 0.02,
  minOuterArea: 1e-3,
  typeOverrides: { "TH-10": "metropolitan_city" },
  names: {
    "TH-10": { ja: "バンコク都",            en: "Bangkok", note: "首都" },
    "TH-11": { ja: "サムットプラーカーン県",en: "Samut Prakan" },
    "TH-12": { ja: "ノンタブリー県",        en: "Nonthaburi" },
    "TH-13": { ja: "パトゥムターニー県",    en: "Pathum Thani" },
    "TH-14": { ja: "アユタヤ県",            en: "Phra Nakhon Si Ayutthaya" },
    "TH-15": { ja: "アーントーン県",        en: "Ang Thong" },
    "TH-16": { ja: "ロッブリー県",          en: "Lop Buri" },
    "TH-17": { ja: "シンブリー県",          en: "Sing Buri" },
    "TH-18": { ja: "チャイナート県",        en: "Chai Nat" },
    "TH-19": { ja: "サラブリー県",          en: "Saraburi" },
    "TH-20": { ja: "チョンブリー県",        en: "Chon Buri" },
    "TH-21": { ja: "ラヨーン県",            en: "Rayong" },
    "TH-22": { ja: "チャンタブリー県",      en: "Chanthaburi" },
    "TH-23": { ja: "トラート県",            en: "Trat" },
    "TH-24": { ja: "チャチューンサオ県",    en: "Chachoengsao" },
    "TH-25": { ja: "プラーチーンブリー県",  en: "Prachin Buri" },
    "TH-26": { ja: "ナコーンナーヨック県",  en: "Nakhon Nayok" },
    "TH-27": { ja: "サケーオ県",            en: "Sa Kaeo" },
    "TH-30": { ja: "ナコーンラーチャシーマー県", en: "Nakhon Ratchasima" },
    "TH-31": { ja: "ブリーラム県",          en: "Buri Ram" },
    "TH-32": { ja: "スリン県",              en: "Surin" },
    "TH-33": { ja: "シーサケート県",        en: "Si Sa Ket" },
    "TH-34": { ja: "ウボンラーチャターニー県", en: "Ubon Ratchathani" },
    "TH-35": { ja: "ヤソートーン県",        en: "Yasothon" },
    "TH-36": { ja: "チャイヤプーム県",      en: "Chaiyaphum" },
    "TH-37": { ja: "アムナートチャルーン県",en: "Amnat Charoen" },
    "TH-38": { ja: "ブンカーン県",          en: "Bueng Kan" },
    "TH-39": { ja: "ノーンブワラムプー県",  en: "Nong Bua Lam Phu" },
    "TH-40": { ja: "コーンケン県",          en: "Khon Kaen" },
    "TH-41": { ja: "ウドーンターニー県",    en: "Udon Thani" },
    "TH-42": { ja: "ルーイ県",              en: "Loei" },
    "TH-43": { ja: "ノーンカーイ県",        en: "Nong Khai" },
    "TH-44": { ja: "マハーサーラカーム県",  en: "Maha Sarakham" },
    "TH-45": { ja: "ロイエット県",          en: "Roi Et" },
    "TH-46": { ja: "カーラシン県",          en: "Kalasin" },
    "TH-47": { ja: "サコンナコーン県",      en: "Sakon Nakhon" },
    "TH-48": { ja: "ナコーンパノム県",      en: "Nakhon Phanom" },
    "TH-49": { ja: "ムックダーハーン県",    en: "Mukdahan" },
    "TH-50": { ja: "チエンマイ県",          en: "Chiang Mai" },
    "TH-51": { ja: "ラムプーン県",          en: "Lamphun" },
    "TH-52": { ja: "ラムパーン県",          en: "Lampang" },
    "TH-53": { ja: "ウタラディット県",      en: "Uttaradit" },
    "TH-54": { ja: "プレー県",              en: "Phrae" },
    "TH-55": { ja: "ナーン県",              en: "Nan" },
    "TH-56": { ja: "パヤオ県",              en: "Phayao" },
    "TH-57": { ja: "チエンラーイ県",        en: "Chiang Rai" },
    "TH-58": { ja: "メーホンソーン県",      en: "Mae Hong Son" },
    "TH-60": { ja: "ナコーンサワン県",      en: "Nakhon Sawan" },
    "TH-61": { ja: "ウタイターニー県",      en: "Uthai Thani" },
    "TH-62": { ja: "カムペーンペット県",    en: "Kamphaeng Phet" },
    "TH-63": { ja: "ターク県",              en: "Tak" },
    "TH-64": { ja: "スコータイ県",          en: "Sukhothai" },
    "TH-65": { ja: "ピッサヌローク県",      en: "Phitsanulok" },
    "TH-66": { ja: "ピチット県",            en: "Phichit" },
    "TH-67": { ja: "ペッチャブーン県",      en: "Phetchabun" },
    "TH-70": { ja: "ラーチャブリー県",      en: "Ratchaburi" },
    "TH-71": { ja: "カーンチャナブリー県",  en: "Kanchanaburi" },
    "TH-72": { ja: "スパンブリー県",        en: "Suphan Buri" },
    "TH-73": { ja: "ナコーンパトム県",      en: "Nakhon Pathom" },
    "TH-74": { ja: "サムットサーコーン県",  en: "Samut Sakhon" },
    "TH-75": { ja: "サムットソンクラーム県",en: "Samut Songkhram" },
    "TH-76": { ja: "ペッチャブリー県",      en: "Phetchaburi" },
    "TH-77": { ja: "プラチュワップキーリーカン県", en: "Prachuap Khiri Khan" },
    "TH-80": { ja: "ナコーンシータマラート県", en: "Nakhon Si Thammarat" },
    "TH-81": { ja: "クラビー県",            en: "Krabi" },
    "TH-82": { ja: "パンガー県",            en: "Phangnga" },
    "TH-83": { ja: "プーケット県",          en: "Phuket" },
    "TH-84": { ja: "スラートターニー県",    en: "Surat Thani" },
    "TH-85": { ja: "ラノーン県",            en: "Ranong" },
    "TH-86": { ja: "チュムポーン県",        en: "Chumphon" },
    "TH-90": { ja: "ソンクラー県",          en: "Songkhla" },
    "TH-91": { ja: "サトゥーン県",          en: "Satun" },
    "TH-92": { ja: "トラン県",              en: "Trang" },
    "TH-93": { ja: "パッタルン県",          en: "Phatthalung" },
    "TH-94": { ja: "パッターニー県",        en: "Pattani" },
    "TH-95": { ja: "ヤラー県",              en: "Yala" },
    "TH-96": { ja: "ナラーティワート県",    en: "Narathiwat" },
  },
};
