// Turkey: 81 provinces (il)
module.exports = {
  pageDir: "middle_east/turkey",
  source: { type: "natural-earth", iso_a2: "TR" },
  title: { ja: "トルコの県", en: "Provinces of Turkey" },
  defaultType: "province",
  tolerance: 0.015,
  minOuterArea: 1e-3,
  names: {
    "TR-01": { ja: "アダナ県",         en: "Adana" },
    "TR-02": { ja: "アドゥヤマン県",   en: "Adıyaman" },
    "TR-03": { ja: "アフィヨンカラヒサール県", en: "Afyonkarahisar" },
    "TR-04": { ja: "アール県",         en: "Ağrı" },
    "TR-05": { ja: "アマスィヤ県",     en: "Amasya" },
    "TR-06": { ja: "アンカラ県",       en: "Ankara", note: "首都" },
    "TR-07": { ja: "アンタルヤ県",     en: "Antalya" },
    "TR-08": { ja: "アルトヴィン県",   en: "Artvin" },
    "TR-09": { ja: "アイドゥン県",     en: "Aydın" },
    "TR-10": { ja: "バルケスィル県",   en: "Balıkesir" },
    "TR-11": { ja: "ビレジク県",       en: "Bilecik" },
    "TR-12": { ja: "ビンギョル県",     en: "Bingöl" },
    "TR-13": { ja: "ビトリス県",       en: "Bitlis" },
    "TR-14": { ja: "ボル県",           en: "Bolu" },
    "TR-15": { ja: "ブルドゥル県",     en: "Burdur" },
    "TR-16": { ja: "ブルサ県",         en: "Bursa" },
    "TR-17": { ja: "チャナッカレ県",   en: "Çanakkale" },
    "TR-18": { ja: "チャンクル県",     en: "Çankırı" },
    "TR-19": { ja: "チョルム県",       en: "Çorum" },
    "TR-20": { ja: "デニズリ県",       en: "Denizli" },
    "TR-21": { ja: "ディヤルバクル県", en: "Diyarbakır" },
    "TR-22": { ja: "エディルネ県",     en: "Edirne" },
    "TR-23": { ja: "エラズー県",       en: "Elazığ" },
    "TR-24": { ja: "エルズィンジャン県", en: "Erzincan" },
    "TR-25": { ja: "エルズルム県",     en: "Erzurum" },
    "TR-26": { ja: "エスキシェヒル県", en: "Eskişehir" },
    "TR-27": { ja: "ガズィアンテプ県", en: "Gaziantep" },
    "TR-28": { ja: "ギレスン県",       en: "Giresun" },
    "TR-29": { ja: "ギュミュシュハネ県", en: "Gümüşhane" },
    "TR-30": { ja: "ハッキャリ県",     en: "Hakkâri" },
    "TR-31": { ja: "ハタイ県",         en: "Hatay" },
    "TR-32": { ja: "ウスパルタ県",     en: "Isparta" },
    "TR-33": { ja: "メルスィン県",     en: "Mersin" },
    "TR-34": { ja: "イスタンブール県", en: "Istanbul" },
    "TR-35": { ja: "イズミル県",       en: "İzmir" },
    "TR-36": { ja: "カルス県",         en: "Kars" },
    "TR-37": { ja: "カスタモヌ県",     en: "Kastamonu" },
    "TR-38": { ja: "カイセリ県",       en: "Kayseri" },
    "TR-39": { ja: "クルクラーレリ県", en: "Kırklareli" },
    "TR-40": { ja: "クルシェヒル県",   en: "Kırşehir" },
    "TR-41": { ja: "コジャエリ県",     en: "Kocaeli" },
    "TR-42": { ja: "コンヤ県",         en: "Konya" },
    "TR-43": { ja: "キュタヒヤ県",     en: "Kütahya" },
    "TR-44": { ja: "マラティヤ県",     en: "Malatya" },
    "TR-45": { ja: "マニサ県",         en: "Manisa" },
    "TR-46": { ja: "カフラマンマラシュ県", en: "Kahramanmaraş" },
    "TR-47": { ja: "マルディン県",     en: "Mardin" },
    "TR-48": { ja: "ムーラ県",         en: "Muğla" },
    "TR-49": { ja: "ムシュ県",         en: "Muş" },
    "TR-50": { ja: "ネヴシェヒル県",   en: "Nevşehir" },
    "TR-51": { ja: "ニーデ県",         en: "Niğde" },
    "TR-52": { ja: "オルドゥ県",       en: "Ordu" },
    "TR-53": { ja: "リゼ県",           en: "Rize" },
    "TR-54": { ja: "サカリヤ県",       en: "Sakarya" },
    "TR-55": { ja: "サムスン県",       en: "Samsun" },
    "TR-56": { ja: "シイルト県",       en: "Siirt" },
    "TR-57": { ja: "スィノプ県",       en: "Sinop" },
    "TR-58": { ja: "スィヴァス県",     en: "Sivas" },
    "TR-59": { ja: "テキルダー県",     en: "Tekirdağ" },
    "TR-60": { ja: "トカット県",       en: "Tokat" },
    "TR-61": { ja: "トラブゾン県",     en: "Trabzon" },
    "TR-62": { ja: "トゥンジェリ県",   en: "Tunceli" },
    "TR-63": { ja: "シャンルウルファ県", en: "Şanlıurfa" },
    "TR-64": { ja: "ウシャク県",       en: "Uşak" },
    "TR-65": { ja: "ヴァン県",         en: "Van" },
    "TR-66": { ja: "ヨズガト県",       en: "Yozgat" },
    "TR-67": { ja: "ゾングルダク県",   en: "Zonguldak" },
    "TR-68": { ja: "アクサライ県",     en: "Aksaray" },
    "TR-69": { ja: "バイブルト県",     en: "Bayburt" },
    "TR-70": { ja: "カラマン県",       en: "Karaman" },
    "TR-71": { ja: "クルッカレ県",     en: "Kırıkkale" },
    "TR-72": { ja: "バトマン県",       en: "Batman" },
    "TR-73": { ja: "シュルナク県",     en: "Şırnak" },
    "TR-74": { ja: "バルトゥン県",     en: "Bartın" },
    "TR-75": { ja: "アルダハン県",     en: "Ardahan" },
    "TR-76": { ja: "ウードゥル県",     en: "Iğdır" },
    "TR-77": { ja: "ヤロヴァ県",       en: "Yalova" },
    "TR-78": { ja: "カラビュク県",     en: "Karabük" },
    "TR-79": { ja: "キリス県",         en: "Kilis" },
    "TR-80": { ja: "オスマニエ県",     en: "Osmaniye" },
    "TR-81": { ja: "デュズジェ県",     en: "Düzce" },
  },
};
