// Ukraine: 24 oblasts + Crimea + 2 cities (Kyiv, Sevastopol). NE has 25.
module.exports = {
  pageDir: "europe/ukraine",
  source: { type: "natural-earth", iso_a2: "UA" },
  title: { ja: "ウクライナの州", en: "Oblasts of Ukraine" },
  defaultType: "oblast",
  tolerance: 0.02,
  minOuterArea: 1e-3,
  typeOverrides: { "UA-30": "metropolitan_city", "UA-40": "metropolitan_city" },
  names: {
    "UA-71": { ja: "チェルカースィ州", en: "Cherkasy" },
    "UA-74": { ja: "チェルニーヒウ州", en: "Chernihiv" },
    "UA-77": { ja: "チェルニウツィー州", en: "Chernivtsi" },
    "UA-12": { ja: "ドニプロペトロウシク州", en: "Dnipropetrovsk" },
    "UA-14": { ja: "ドネツク州",      en: "Donetsk" },
    "UA-26": { ja: "イヴァーノ・フランキーウシク州", en: "Ivano-Frankivsk" },
    "UA-63": { ja: "ハルキウ州",      en: "Kharkiv" },
    "UA-65": { ja: "ヘルソン州",      en: "Kherson" },
    "UA-68": { ja: "フメリヌィーツィクィイ州", en: "Khmelnytskyi" },
    "UA-35": { ja: "キロヴォフラード州", en: "Kirovohrad" },
    "UA-32": { ja: "キーウ州",        en: "Kyiv (Oblast)" },
    "UA-30": { ja: "キーウ市",        en: "Kyiv (City)", note: "首都" },
    "UA-09": { ja: "ルハーンシク州",  en: "Luhansk" },
    "UA-46": { ja: "リヴィウ州",      en: "Lviv" },
    "UA-48": { ja: "ミコライウ州",    en: "Mykolaiv" },
    "UA-51": { ja: "オデーサ州",      en: "Odesa" },
    "UA-53": { ja: "ポルタヴァ州",    en: "Poltava" },
    "UA-56": { ja: "リウネ州",        en: "Rivne" },
    "UA-59": { ja: "スームィ州",      en: "Sumy" },
    "UA-61": { ja: "テルノーピリ州",  en: "Ternopil" },
    "UA-05": { ja: "ヴィーンヌィツャ州", en: "Vinnytsia" },
    "UA-07": { ja: "ヴォルィーニ州",  en: "Volyn" },
    "UA-21": { ja: "ザカルパッチャ州",en: "Zakarpattia" },
    "UA-23": { ja: "ザポリージャ州",  en: "Zaporizhzhia" },
    "UA-18": { ja: "ジトームィル州",  en: "Zhytomyr" },
    "UA-43": { ja: "クリミア自治共和国", en: "Crimea", note: "係争地域" },
    "UA-40": { ja: "セヴァストポリ",  en: "Sevastopol", note: "係争地域" },
  },
};
