// USA: 50 states + DC. Default render excludes Alaska & Hawaii from the SVG
// so the contiguous 48 stays at a readable scale; both still appear in the
// list (no SVG hover for them, but they're labeled).
module.exports = {
  pageDir: "n_america/usa",
  source: { type: "natural-earth", iso_a2: "US" },
  title: { ja: "アメリカの州", en: "States of the United States" },
  defaultType: "state",
  tolerance: 0.05,
  minOuterArea: 5e-3,
  // Hide AK / HI / outlying territories on the map but keep them in the list.
  svgExcludeCodes: ["US-AK", "US-HI"],
  typeOverrides: { "US-DC": "federal_district" },
  names: {
    "US-AL": { ja: "アラバマ州",        en: "Alabama" },
    "US-AK": { ja: "アラスカ州",        en: "Alaska" },
    "US-AZ": { ja: "アリゾナ州",        en: "Arizona" },
    "US-AR": { ja: "アーカンソー州",    en: "Arkansas" },
    "US-CA": { ja: "カリフォルニア州",  en: "California" },
    "US-CO": { ja: "コロラド州",        en: "Colorado" },
    "US-CT": { ja: "コネチカット州",    en: "Connecticut" },
    "US-DE": { ja: "デラウェア州",      en: "Delaware" },
    "US-FL": { ja: "フロリダ州",        en: "Florida" },
    "US-GA": { ja: "ジョージア州",      en: "Georgia" },
    "US-HI": { ja: "ハワイ州",          en: "Hawaii" },
    "US-ID": { ja: "アイダホ州",        en: "Idaho" },
    "US-IL": { ja: "イリノイ州",        en: "Illinois" },
    "US-IN": { ja: "インディアナ州",    en: "Indiana" },
    "US-IA": { ja: "アイオワ州",        en: "Iowa" },
    "US-KS": { ja: "カンザス州",        en: "Kansas" },
    "US-KY": { ja: "ケンタッキー州",    en: "Kentucky" },
    "US-LA": { ja: "ルイジアナ州",      en: "Louisiana" },
    "US-ME": { ja: "メイン州",          en: "Maine" },
    "US-MD": { ja: "メリーランド州",    en: "Maryland" },
    "US-MA": { ja: "マサチューセッツ州",en: "Massachusetts" },
    "US-MI": { ja: "ミシガン州",        en: "Michigan" },
    "US-MN": { ja: "ミネソタ州",        en: "Minnesota" },
    "US-MS": { ja: "ミシシッピ州",      en: "Mississippi" },
    "US-MO": { ja: "ミズーリ州",        en: "Missouri" },
    "US-MT": { ja: "モンタナ州",        en: "Montana" },
    "US-NE": { ja: "ネブラスカ州",      en: "Nebraska" },
    "US-NV": { ja: "ネバダ州",          en: "Nevada" },
    "US-NH": { ja: "ニューハンプシャー州", en: "New Hampshire" },
    "US-NJ": { ja: "ニュージャージー州",en: "New Jersey" },
    "US-NM": { ja: "ニューメキシコ州",  en: "New Mexico" },
    "US-NY": { ja: "ニューヨーク州",    en: "New York" },
    "US-NC": { ja: "ノースカロライナ州",en: "North Carolina" },
    "US-ND": { ja: "ノースダコタ州",    en: "North Dakota" },
    "US-OH": { ja: "オハイオ州",        en: "Ohio" },
    "US-OK": { ja: "オクラホマ州",      en: "Oklahoma" },
    "US-OR": { ja: "オレゴン州",        en: "Oregon" },
    "US-PA": { ja: "ペンシルベニア州",  en: "Pennsylvania" },
    "US-RI": { ja: "ロードアイランド州",en: "Rhode Island" },
    "US-SC": { ja: "サウスカロライナ州",en: "South Carolina" },
    "US-SD": { ja: "サウスダコタ州",    en: "South Dakota" },
    "US-TN": { ja: "テネシー州",        en: "Tennessee" },
    "US-TX": { ja: "テキサス州",        en: "Texas" },
    "US-UT": { ja: "ユタ州",            en: "Utah" },
    "US-VT": { ja: "バーモント州",      en: "Vermont" },
    "US-VA": { ja: "バージニア州",      en: "Virginia" },
    "US-WA": { ja: "ワシントン州",      en: "Washington" },
    "US-WV": { ja: "ウェストバージニア州", en: "West Virginia" },
    "US-WI": { ja: "ウィスコンシン州",  en: "Wisconsin" },
    "US-WY": { ja: "ワイオミング州",    en: "Wyoming" },
    "US-DC": { ja: "コロンビア特別区",  en: "District of Columbia", note: "首都" },
  },
};
