// Vietnam: 58 provinces + 5 centrally-governed cities. NE has 63 entries
// + 3 legacy regional entries which we filter out.
module.exports = {
  pageDir: "asia/vietnum", // existing typo in repo path
  source: { type: "natural-earth", iso_a2: "VN" },
  title: { ja: "ベトナムの省・直轄市", en: "Provinces of Vietnam" },
  defaultType: "province",
  tolerance: 0.02,
  minOuterArea: 1e-3,
  // Drop legacy regional entries (Đông Bắc, Đông Nam Bộ, Đồng Bằng Sông Hồng)
  excludeCodes: ["VN-39", "VN-53", "VN-66"],
  typeOverrides: {
    "VN-HN": "metropolitan_city",
    "VN-SG": "metropolitan_city",
    "VN-HP": "metropolitan_city",
    "VN-DN": "metropolitan_city",
    "VN-CT": "metropolitan_city",
  },
  names: {
    "VN-HN": { ja: "ハノイ",            en: "Hanoi", note: "首都" },
    "VN-SG": { ja: "ホーチミン市",      en: "Ho Chi Minh City" },
    "VN-HP": { ja: "ハイフォン",        en: "Haiphong" },
    "VN-DN": { ja: "ダナン",            en: "Da Nang" },
    "VN-CT": { ja: "カントー",          en: "Can Tho" },
    "VN-26": { ja: "トゥアティエン・フエ省", en: "Thừa Thiên-Huế" },
    "VN-34": { ja: "カインホア省",      en: "Khánh Hòa" },
    "VN-21": { ja: "タインホア省",      en: "Thanh Hóa" },
    "VN-22": { ja: "ゲアン省",          en: "Nghệ An" },
    "VN-44": { ja: "アンザン省",        en: "An Giang" },
    "VN-47": { ja: "キエンザン省",      en: "Kiên Giang" },
    "VN-43": { ja: "バリア・ブンタウ省",en: "Bà Rịa-Vũng Tàu" },
    "VN-35": { ja: "ラムドン省",        en: "Lâm Đồng" },
    "VN-57": { ja: "ビンズオン省",      en: "Bình Dương" },
    "VN-58": { ja: "ビンフオック省",    en: "Bình Phước" },
    "VN-32": { ja: "フーイエン省",      en: "Phú Yên" },
    "VN-31": { ja: "ビンディン省",      en: "Bình Định" },
    "VN-29": { ja: "クアンガイ省",      en: "Quảng Ngãi" },
    "VN-27": { ja: "クアンナム省",      en: "Quảng Nam" },
    "VN-25": { ja: "クアンチ省",        en: "Quảng Trị" },
    "VN-24": { ja: "クアンビン省",      en: "Quảng Bình" },
    "VN-23": { ja: "ハティン省",        en: "Hà Tĩnh" },
    "VN-13": { ja: "クアンニン省",      en: "Quảng Ninh" },
    "VN-09": { ja: "ランソン省",        en: "Lạng Sơn" },
    "VN-04": { ja: "カオバン省",        en: "Cao Bằng" },
    "VN-03": { ja: "ハザン省",          en: "Hà Giang" },
    "VN-02": { ja: "ラオカイ省",        en: "Lào Cai" },
    "VN-01": { ja: "ライチャウ省",      en: "Lai Châu" },
    "VN-71": { ja: "ディエンビエン省",  en: "Điện Biên" },
    "VN-05": { ja: "ソンラ省",          en: "Sơn La" },
    "VN-14": { ja: "ホアビン省",        en: "Hòa Bình" },
    "VN-06": { ja: "イエンバイ省",      en: "Yên Bái" },
    "VN-07": { ja: "トゥエンクアン省",  en: "Tuyên Quang" },
    "VN-68": { ja: "フート省",          en: "Phú Thọ" },
    "VN-69": { ja: "タイグエン省",      en: "Thái Nguyên" },
    "VN-70": { ja: "ヴィンフック省",    en: "Vĩnh Phúc" },
    "VN-54": { ja: "バクザン省",        en: "Bắc Giang" },
    "VN-56": { ja: "バクニン省",        en: "Bắc Ninh" },
    "VN-61": { ja: "ハイズオン省",      en: "Hải Dương" },
    "VN-20": { ja: "タイビン省",        en: "Thái Bình" },
    "VN-67": { ja: "ナムディン省",      en: "Nam Định" },
    "VN-63": { ja: "ハナム省",          en: "Hà Nam" },
    "VN-18": { ja: "ニンビン省",        en: "Ninh Bình" },
    "VN-30": { ja: "ザライ省",          en: "Gia Lai" },
    "VN-28": { ja: "コントゥム省",      en: "Kon Tum" },
    "VN-33": { ja: "ダクラク省",        en: "Đắk Lắk" },
    "VN-72": { ja: "ダクノン省",        en: "Đắk Nông" },
    "VN-36": { ja: "ニントゥアン省",    en: "Ninh Thuận" },
    "VN-40": { ja: "ビントゥアン省",    en: "Bình Thuận" },
    "VN-37": { ja: "タイニン省",        en: "Tây Ninh" },
    "VN-41": { ja: "ロンアン省",        en: "Long An" },
    "VN-45": { ja: "ドンタップ省",      en: "Đồng Tháp" },
    "VN-46": { ja: "ティエンザン省",    en: "Tiền Giang" },
    "VN-50": { ja: "ベンチェ省",        en: "Bến Tre" },
    "VN-49": { ja: "ヴィンロン省",      en: "Vĩnh Long" },
    "VN-51": { ja: "チャヴィン省",      en: "Trà Vinh" },
    "VN-52": { ja: "ソクチャン省",      en: "Sóc Trăng" },
    "VN-55": { ja: "バクリエウ省",      en: "Bạc Liêu" },
    "VN-59": { ja: "カマウ省",          en: "Cà Mau" },
    "VN-73": { ja: "ハウザン省",        en: "Hậu Giang" },
  },
};
