/**
 * Municipality list + boundary SVG renderer.
 *
 * Reads `municipalities` from the page's frontmatter and produces an HTML
 * block to inject between the pref-info section and `<div id="corp-desc">`.
 * Pairs with the SVG generated by scripts/generate-prefecture-municipality-svg.cjs.
 */
import fs from "node:fs";
import path from "node:path";
import type { Language } from "../../../lib/i18n-utils.ts";

export interface MunicipalityItem {
  code: string;
  name: string;
  /**
   * Built-in Japan types get localized labels and grouped order; any other
   * string falls through as a custom group label (used as-is).
   */
  type?: string;
  note?: string;
}

export interface MunicipalitiesData {
  svg: string;
  /** Optional override for the section heading (defaults to "{title}の自治体"). */
  title?: string;
  asOf?: string;
  source?: string;
  sourceUrl?: string;
  list: MunicipalityItem[];
}

const TITLE: Record<Language, (name: string) => string> = {
  ja: (n) => `${n}の自治体`,
  en: (n) => `Municipalities of ${n}`,
  id: (n) => `Munisipalitas di ${n}`,
  es: (n) => `Municipios de ${n}`,
  pt: (n) => `Municípios de ${n}`,
};

const TYPE_LABEL: Record<string, Record<Language, string>> = {
  city: { ja: "市", en: "City", id: "Kota", es: "Ciudad", pt: "Cidade" },
  town: { ja: "町", en: "Town", id: "Kota kecil", es: "Pueblo", pt: "Vila" },
  village: { ja: "村", en: "Village", id: "Desa", es: "Aldea", pt: "Aldeia" },
  ward: { ja: "区", en: "Ward", id: "Distrik", es: "Distrito", pt: "Distrito" },
  // Common non-Japan types — extend as needed
  metropolitan_city: {
    ja: "広域市・特別市",
    en: "Metropolitan City",
    id: "Kota metropolitan",
    es: "Ciudad metropolitana",
    pt: "Cidade metropolitana",
  },
  province: {
    ja: "道",
    en: "Province",
    id: "Provinsi",
    es: "Provincia",
    pt: "Província",
  },
  state: {
    ja: "州",
    en: "State",
    id: "Negara bagian",
    es: "Estado",
    pt: "Estado",
  },
};

const ALT_LABEL: Record<Language, (n: string) => string> = {
  ja: (n) => `${n}の自治体境界図`,
  en: (n) => `Municipality boundaries of ${n}`,
  id: (n) => `Peta batas munisipalitas ${n}`,
  es: (n) => `Mapa de los municipios de ${n}`,
  pt: (n) => `Mapa dos municípios de ${n}`,
};

function pick<T>(map: Record<Language, T>, lang: Language): T {
  return map[lang] ?? map.ja;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// Built-in render order for known types. Unknown types are rendered after
// these in the order they first appear in the frontmatter.
const TYPE_ORDER: string[] = [
  "metropolitan_city",
  "province",
  "state",
  "city",
  "ward",
  "town",
  "village",
];

export function renderMunicipalitiesHtml(
  data: MunicipalitiesData,
  pageTitle: string,
  lang: Language
): string {
  if (!data.list || data.list.length === 0) return "";

  // Group by type, preserving frontmatter order within each group.
  const groups = new Map<string, MunicipalityItem[]>();
  const ungrouped: MunicipalityItem[] = [];
  for (const m of data.list) {
    if (m.type) {
      const arr = groups.get(m.type) ?? [];
      arr.push(m);
      groups.set(m.type, arr);
    } else {
      ungrouped.push(m);
    }
  }

  // Order: known types in TYPE_ORDER first, then any custom types in
  // first-seen order from the frontmatter.
  const seenOrder: string[] = [];
  for (const m of data.list) {
    if (m.type && !seenOrder.includes(m.type)) seenOrder.push(m.type);
  }
  const orderedTypes = [
    ...TYPE_ORDER.filter((t) => groups.has(t)),
    ...seenOrder.filter((t) => !TYPE_ORDER.includes(t)),
  ];

  const groupHtml: string[] = [];
  for (const t of orderedTypes) {
    const items = groups.get(t);
    if (!items || items.length === 0) continue;
    // Known types get localized labels; unknown types render the raw value.
    const label = TYPE_LABEL[t] ? pick(TYPE_LABEL[t], lang) : t;
    const lis = items
      .map((m) => {
        const note = m.note
          ? `<span class="pref-muni-list__note">${esc(m.note)}</span>`
          : "";
        return `            <li data-code="${esc(m.code)}"><span class="pref-muni-list__name">${esc(m.name)}</span>${note}</li>`;
      })
      .join("\n");
    groupHtml.push(
      `        <div class="pref-muni-list__group" data-type="${esc(t)}">
          <div class="pref-muni-list__group-label"><span class="pref-muni-list__type">${esc(label)}</span><span class="pref-muni-list__count">${items.length}</span></div>
          <ul class="pref-muni-list__items">
${lis}
          </ul>
        </div>`
    );
  }
  if (ungrouped.length > 0) {
    const lis = ungrouped
      .map(
        (m) =>
          `            <li data-code="${esc(m.code)}"><span class="pref-muni-list__name">${esc(m.name)}</span>${
            m.note ? `<span class="pref-muni-list__note">${esc(m.note)}</span>` : ""
          }</li>`
      )
      .join("\n");
    groupHtml.push(
      `        <div class="pref-muni-list__group" data-type="other">
          <ul class="pref-muni-list__items">
${lis}
          </ul>
        </div>`
    );
  }

  const total = data.list.length;
  const altText = esc(pick(ALT_LABEL, lang)(pageTitle));

  // Inline the SVG so list-hover ↔ path-highlight can work via shared DOM.
  // The svg field starts with "/" (a public/-relative URL); resolve it
  // against the project's public/ directory.
  let inlinedSvg = "";
  if (data.svg && data.svg.startsWith("/")) {
    try {
      const filePath = path.join(
        process.cwd(),
        "public",
        data.svg.replace(/^\/+/, "")
      );
      const raw = fs.readFileSync(filePath, "utf8");
      // Strip <?xml ... ?> declaration; keep <svg ...>...</svg>.
      // Add aria-label and role to the inlined root if not already set.
      let body = raw.replace(/^\s*<\?xml[^?]*\?>\s*/, "").trim();
      if (!/aria-label=/.test(body)) {
        body = body.replace(
          /<svg\b/,
          `<svg aria-label="${altText}"`
        );
      }
      inlinedSvg = body;
    } catch {
      // Fall back to <img> below if file not found
      inlinedSvg = "";
    }
  }
  const mapInner = inlinedSvg
    ? inlinedSvg
    : `<img src="${esc(data.svg)}" alt="${altText}" loading="lazy" decoding="async" />`;

  // Hover sync: highlight matching SVG path when a list item is hovered,
  // and vice-versa. Pure-DOM, no framework, scoped to this section.
  const hoverScript = inlinedSvg
    ? `<script>(function(){
  var root = document.getElementById('pref-muni');
  if (!root) return;
  var paths = root.querySelectorAll('svg [data-code]');
  var items = root.querySelectorAll('.pref-muni-list__items li[data-code]');
  function setActive(code, on) {
    if (!code) return;
    paths.forEach(function(p) {
      if (p.getAttribute('data-code') === code) p.classList.toggle('is-active', on);
    });
    items.forEach(function(li) {
      if (li.getAttribute('data-code') === code) li.classList.toggle('is-active', on);
    });
  }
  function bind(el) {
    var code = el.getAttribute('data-code');
    el.addEventListener('mouseenter', function(){ setActive(code, true); });
    el.addEventListener('mouseleave', function(){ setActive(code, false); });
  }
  items.forEach(bind);
  paths.forEach(bind);
})();</script>`
    : "";

  const sectionTitle = data.title
    ? data.title
    : pick(TITLE, lang)(pageTitle);

  return `<section class="pref-muni-section" id="pref-muni">
    <h4 class="pref-muni-section__title">${esc(sectionTitle)} <span class="pref-muni-section__total">(${total})</span></h4>
    <div class="pref-muni-layout">
      <div class="pref-muni-map">
${mapInner}
      </div>
      <div class="pref-muni-list">
${groupHtml.join("\n")}
      </div>
    </div>
${hoverScript}
</section>`;
}
